// AUTO-GENERATED by scripts/generate-setup-sql.js — DO NOT EDIT.
// Source of truth: lib/db/setup.sql
// Run `pnpm run generate-module-registry` to regenerate.
export const setupSql = `-- ================================================================
-- ARI Database Setup
-- Creates all required tables with Row Level Security (RLS)
-- Run this in your SQL client (Supabase Studio, pgweb, or psql) before first use
-- NOTE: Keep in sync with lib/db/setup-sql.ts (TS export for /welcome)
-- ================================================================

BEGIN;

SET session_replication_role = 'replica';

-- ================================================================
-- APP FUNCTION (used by RLS policies)
-- ================================================================

CREATE SCHEMA IF NOT EXISTS app;
CREATE OR REPLACE FUNCTION app.current_user_id()
RETURNS TEXT AS $$
  SELECT current_setting('app.current_user_id', true);
$$ LANGUAGE sql STABLE SET search_path = '';

-- ================================================================
-- AUTH TABLES (user must come first - referenced by others)
-- ================================================================

-- Table: user
CREATE TABLE IF NOT EXISTS "user" (
  "id" TEXT NOT NULL,
  "name" TEXT,
  "email" TEXT NOT NULL,
  "emailVerified" BOOLEAN DEFAULT FALSE,
  "image" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "firstName" TEXT,
  "lastName" TEXT,
  "twoFactorEnabled" BOOLEAN DEFAULT FALSE,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_email_key" UNIQUE ("email")
);
ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_rls_deny" ON "user" FOR ALL TO public USING (false);

-- Table: session
CREATE TABLE IF NOT EXISTS "session" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "session_token_key" UNIQUE ("token")
);
ALTER TABLE "session" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "session_rls_deny" ON "session" FOR ALL TO public USING (false);

-- Table: account
CREATE TABLE IF NOT EXISTS "account" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMPTZ,
  "refreshTokenExpiresAt" TIMESTAMPTZ,
  "scope" TEXT,
  "idToken" TEXT,
  "password" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "account" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "account_rls_deny" ON "account" FOR ALL TO public USING (false);

-- Table: twoFactor
CREATE TABLE IF NOT EXISTS "twoFactor" (
  "id" TEXT NOT NULL DEFAULT gen_random_uuid(),
  "secret" TEXT NOT NULL,
  "backupCodes" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE "twoFactor" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "twoFactor_rls_deny" ON "twoFactor" FOR ALL TO public USING (false);

-- Table: verification
CREATE TABLE IF NOT EXISTS "verification" (
  "id" TEXT NOT NULL,
  "identifier" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "verification" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "verification_rls_deny" ON "verification" FOR ALL TO public USING (false);

-- ================================================================
-- SYSTEM TABLES
-- ================================================================

-- Table: user_preferences
CREATE TABLE IF NOT EXISTS "user_preferences" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" TEXT NOT NULL,
  "name" VARCHAR(255),
  "email" VARCHAR(255),
  "title" VARCHAR(255),
  "company_name" VARCHAR(255),
  "country" VARCHAR(100),
  "city" VARCHAR(100),
  "linkedin_url" VARCHAR(500),
  "timezone" VARCHAR(50),
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "user_preferences_user_id_key" UNIQUE ("user_id")
);

ALTER TABLE "user_preferences" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_preferences_rls_select" ON "user_preferences" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "user_preferences_rls_insert" ON "user_preferences" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "user_preferences_rls_update" ON "user_preferences" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "user_preferences_rls_delete" ON "user_preferences" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: module_settings
CREATE TABLE IF NOT EXISTS "module_settings" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" TEXT NOT NULL,
  "module_id" VARCHAR(255) NOT NULL,
  "enabled" BOOLEAN DEFAULT TRUE,
  "settings" JSONB,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "module_settings_user_id_module_id_key" UNIQUE ("user_id", "module_id")
);
ALTER TABLE "module_settings" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "module_settings_rls_select" ON "module_settings" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "module_settings_rls_insert" ON "module_settings" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "module_settings_rls_update" ON "module_settings" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "module_settings_rls_delete" ON "module_settings" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: module_migrations
CREATE TABLE IF NOT EXISTS "module_migrations" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "module_id" VARCHAR(255) NOT NULL,
  "migration_name" VARCHAR(255) NOT NULL,
  "applied_at" TIMESTAMPTZ DEFAULT NOW(),
  "applied_by" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "module_migrations_module_id_migration_name_key" UNIQUE ("module_id", "migration_name")
);
ALTER TABLE "module_migrations" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "module_migrations_rls_deny" ON "module_migrations" FOR ALL TO public USING (false);

-- ================================================================
-- API KEY TABLES
-- ================================================================

-- Table: api_keys
CREATE TABLE IF NOT EXISTS "api_keys" (
  "id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "label" VARCHAR(255) NOT NULL,
  "key_hash" TEXT NOT NULL,
  "key_prefix" VARCHAR(12) NOT NULL,
  "expires_at" TIMESTAMPTZ,
  "allowed_ips" TEXT[],
  "last_used_at" TIMESTAMPTZ,
  "request_count" INTEGER NOT NULL DEFAULT 0,
  "revoked" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "api_keys" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "api_keys_rls_select" ON "api_keys" FOR SELECT TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "api_keys_rls_insert" ON "api_keys" FOR INSERT TO public
  WITH CHECK (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "api_keys_rls_update" ON "api_keys" FOR UPDATE TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "api_keys_rls_delete" ON "api_keys" FOR DELETE TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));

-- Table: api_key_usage_logs
CREATE TABLE IF NOT EXISTS "api_key_usage_logs" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "api_key_id" TEXT NOT NULL REFERENCES "api_keys"("id") ON DELETE CASCADE,
  "user_id" TEXT NOT NULL,
  "endpoint" TEXT NOT NULL,
  "method" VARCHAR(10) NOT NULL,
  "status_code" INTEGER NOT NULL,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "api_key_usage_logs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "api_key_usage_logs_rls_select" ON "api_key_usage_logs" FOR SELECT TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "api_key_usage_logs_rls_insert" ON "api_key_usage_logs" FOR INSERT TO public
  WITH CHECK (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "api_key_usage_logs_rls_update" ON "api_key_usage_logs" FOR UPDATE TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "api_key_usage_logs_rls_delete" ON "api_key_usage_logs" FOR DELETE TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));

-- ================================================================
-- MODULE TABLES
-- ================================================================

-- Table: tasks
CREATE TABLE IF NOT EXISTS "tasks" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "title" TEXT NOT NULL,
  "assignees" TEXT[],
  "due_date" DATE,
  "subtasks_completed" INTEGER DEFAULT 0,
  "subtasks_total" INTEGER DEFAULT 0,
  "status" TEXT,
  "priority" TEXT,
  "pinned" BOOLEAN DEFAULT FALSE,
  "completed" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW(),
  "order_index" INTEGER DEFAULT 0,
  "completion_count" INTEGER DEFAULT 0,
  "user_email" TEXT,
  "user_id" TEXT NOT NULL,
  "impact" INTEGER DEFAULT 3,
  "severity" INTEGER DEFAULT 3,
  "timeliness" INTEGER DEFAULT 3,
  "effort" INTEGER DEFAULT 3,
  "strategic_fit" INTEGER DEFAULT 3,
  "priority_score" NUMERIC DEFAULT 0,
  "project_id" UUID,
  "monster_type" TEXT,
  "monster_colors" JSONB,
  PRIMARY KEY ("id")
);
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tasks_rls_select" ON "tasks" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "tasks_rls_insert" ON "tasks" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "tasks_rls_update" ON "tasks" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "tasks_rls_delete" ON "tasks" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: quotes
CREATE TABLE IF NOT EXISTS "quotes" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" TEXT NOT NULL,
  "quote" TEXT NOT NULL,
  "author" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "quotes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "quotes_rls_select" ON "quotes" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "quotes_rls_insert" ON "quotes" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "quotes_rls_update" ON "quotes" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "quotes_rls_delete" ON "quotes" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: music_playlist
CREATE TABLE IF NOT EXISTS "music_playlist" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" TEXT NOT NULL,
  "youtube_video_id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "music_playlist" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "music_playlist_rls_select" ON "music_playlist" FOR SELECT TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "music_playlist_rls_insert" ON "music_playlist" FOR INSERT TO public
  WITH CHECK (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "music_playlist_rls_update" ON "music_playlist" FOR UPDATE TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "music_playlist_rls_delete" ON "music_playlist" FOR DELETE TO public
  USING (user_id = (SELECT current_setting('app.current_user_id')));

-- Table: notepad
CREATE TABLE IF NOT EXISTS "notepad" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "notepad_user_id_key" UNIQUE ("user_id")
);
ALTER TABLE "notepad" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notepad_rls_select" ON "notepad" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "notepad_rls_insert" ON "notepad" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "notepad_rls_update" ON "notepad" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "notepad_rls_delete" ON "notepad" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: notepad_revisions
CREATE TABLE IF NOT EXISTS "notepad_revisions" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "revision_number" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);
ALTER TABLE "notepad_revisions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notepad_revisions_rls_select" ON "notepad_revisions" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "notepad_revisions_rls_insert" ON "notepad_revisions" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "notepad_revisions_rls_update" ON "notepad_revisions" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "notepad_revisions_rls_delete" ON "notepad_revisions" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: brainstorm_boards
CREATE TABLE IF NOT EXISTS "brainstorm_boards" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" TEXT NOT NULL REFERENCES public."user"("id") ON DELETE CASCADE,
  "name" VARCHAR(200) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "brainstorm_boards" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "brainstorm_boards_rls_select" ON "brainstorm_boards" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_boards_rls_insert" ON "brainstorm_boards" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_boards_rls_update" ON "brainstorm_boards" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_boards_rls_delete" ON "brainstorm_boards" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: brainstorm_nodes
CREATE TABLE IF NOT EXISTS "brainstorm_nodes" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "board_id" UUID NOT NULL REFERENCES "brainstorm_boards"("id") ON DELETE CASCADE,
  "user_id" TEXT NOT NULL REFERENCES public."user"("id") ON DELETE CASCADE,
  "text" TEXT NOT NULL DEFAULT '',
  "x" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "y" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "color" VARCHAR(32) NOT NULL DEFAULT 'slate',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);
ALTER TABLE "brainstorm_nodes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "brainstorm_nodes_rls_select" ON "brainstorm_nodes" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_nodes_rls_insert" ON "brainstorm_nodes" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_nodes_rls_update" ON "brainstorm_nodes" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_nodes_rls_delete" ON "brainstorm_nodes" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- Table: brainstorm_edges
CREATE TABLE IF NOT EXISTS "brainstorm_edges" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "board_id" UUID NOT NULL REFERENCES "brainstorm_boards"("id") ON DELETE CASCADE,
  "user_id" TEXT NOT NULL REFERENCES public."user"("id") ON DELETE CASCADE,
  "source_node_id" UUID NOT NULL REFERENCES "brainstorm_nodes"("id") ON DELETE CASCADE,
  "target_node_id" UUID NOT NULL REFERENCES "brainstorm_nodes"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "brainstorm_edges_no_self_loop" CHECK (source_node_id <> target_node_id),
  CONSTRAINT "brainstorm_edges_unique_pair" UNIQUE (board_id, source_node_id, target_node_id)
);
ALTER TABLE "brainstorm_edges" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "brainstorm_edges_rls_select" ON "brainstorm_edges" FOR SELECT TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_edges_rls_insert" ON "brainstorm_edges" FOR INSERT TO public
  WITH CHECK (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_edges_rls_update" ON "brainstorm_edges" FOR UPDATE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));
CREATE POLICY "brainstorm_edges_rls_delete" ON "brainstorm_edges" FOR DELETE TO public
  USING (user_id::text = (SELECT current_setting('app.current_user_id')));

-- ================================================================
-- ARI INSTANCE (per-install identity for anonymous telemetry)
-- ================================================================

CREATE TABLE IF NOT EXISTS "ari_instance" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "telemetry_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

INSERT INTO "ari_instance" ("telemetry_enabled")
SELECT TRUE
WHERE NOT EXISTS (SELECT 1 FROM "ari_instance");

ALTER TABLE "ari_instance" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ari_instance_rls_deny" ON "ari_instance" FOR ALL TO public USING (false);

-- ================================================================
-- INDEXES
-- ================================================================

CREATE INDEX IF NOT EXISTS idx_user_email ON "user"("email");
CREATE INDEX IF NOT EXISTS idx_session_token ON "session"("token");
CREATE INDEX IF NOT EXISTS idx_session_user_id ON "session"("userId");
CREATE INDEX IF NOT EXISTS idx_account_user_id ON "account"("userId");
CREATE INDEX IF NOT EXISTS idx_twoFactor_user_id ON "twoFactor"("userId");
CREATE INDEX IF NOT EXISTS idx_user_preferences_user_id ON "user_preferences"("user_id");
CREATE INDEX IF NOT EXISTS idx_module_settings_user_id ON "module_settings"("user_id");
CREATE INDEX IF NOT EXISTS idx_module_settings_module_id ON "module_settings"("module_id");
CREATE INDEX IF NOT EXISTS idx_module_migrations_module_id ON "module_migrations"("module_id");
CREATE INDEX IF NOT EXISTS idx_api_keys_key_hash ON "api_keys"("key_hash");
CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON "api_keys"("user_id");
CREATE INDEX IF NOT EXISTS idx_api_key_usage_logs_key_created ON "api_key_usage_logs"("api_key_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS idx_api_key_usage_logs_user_id ON "api_key_usage_logs"("user_id");
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON "tasks"("user_id");
CREATE INDEX IF NOT EXISTS idx_tasks_user_id_completed ON "tasks"("user_id", "completed");
-- Drop legacy duplicate indexes (now defined in module schema.sql files)
DROP INDEX IF EXISTS idx_tasks_completed;
DROP INDEX IF EXISTS idx_tasks_order_index;
DROP INDEX IF EXISTS idx_tasks_created_at;
DROP INDEX IF EXISTS idx_quotes_user_id;
CREATE INDEX IF NOT EXISTS idx_music_playlist_user_id ON "music_playlist"("user_id");
CREATE INDEX IF NOT EXISTS idx_music_playlist_user_position ON "music_playlist"("user_id", "position" ASC);
CREATE INDEX IF NOT EXISTS idx_notepad_user_id ON "notepad"("user_id");
CREATE INDEX IF NOT EXISTS idx_notepad_revisions_user_id ON "notepad_revisions"("user_id");
CREATE INDEX IF NOT EXISTS idx_brainstorm_boards_user_id ON "brainstorm_boards"("user_id");
CREATE INDEX IF NOT EXISTS idx_brainstorm_boards_user_updated ON "brainstorm_boards"("user_id", "updated_at" DESC);
CREATE INDEX IF NOT EXISTS idx_brainstorm_nodes_board_id ON "brainstorm_nodes"("board_id");
CREATE INDEX IF NOT EXISTS idx_brainstorm_nodes_user_board ON "brainstorm_nodes"("user_id", "board_id");
CREATE INDEX IF NOT EXISTS idx_brainstorm_edges_board_id ON "brainstorm_edges"("board_id");
CREATE INDEX IF NOT EXISTS idx_brainstorm_edges_user_board ON "brainstorm_edges"("user_id", "board_id");
CREATE INDEX IF NOT EXISTS idx_brainstorm_edges_source ON "brainstorm_edges"("source_node_id");
CREATE INDEX IF NOT EXISTS idx_brainstorm_edges_target ON "brainstorm_edges"("target_node_id");

SET session_replication_role = 'origin';

COMMIT;

-- ================================================================
-- Backup System RPC Functions
-- ================================================================
-- These functions power the dynamic table discovery used by the
-- backup system at /settings > Backups. Defined OUTSIDE the
-- transaction above so they install on a fresh database without
-- depending on any application table.
-- ================================================================

-- Returns all user (public-schema) tables, excluding system/internal ones.
CREATE OR REPLACE FUNCTION public.get_all_user_tables()
RETURNS TABLE(table_name text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
  SELECT t.table_name::text
  FROM information_schema.tables t
  WHERE t.table_schema = 'public'
    AND t.table_type = 'BASE TABLE'
    AND t.table_name NOT IN (
      'spatial_ref_sys',
      'schema_migrations',
      'pg_stat_statements',
      'geography_columns',
      'geometry_columns'
    )
  ORDER BY t.table_name;
$$;

-- Returns column metadata for every public-schema table in one call.
CREATE OR REPLACE FUNCTION public.get_all_table_columns()
RETURNS TABLE(
  table_name text,
  column_name text,
  data_type text,
  is_nullable text,
  column_default text,
  character_maximum_length integer,
  ordinal_position integer
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
  SELECT
    c.table_name::text,
    c.column_name::text,
    c.data_type::text,
    c.is_nullable::text,
    c.column_default::text,
    c.character_maximum_length::integer,
    c.ordinal_position::integer
  FROM information_schema.columns c
  JOIN information_schema.tables t
    ON t.table_schema = c.table_schema
   AND t.table_name = c.table_name
  WHERE c.table_schema = 'public'
    AND t.table_type = 'BASE TABLE'
  ORDER BY c.table_name, c.ordinal_position;
$$;

-- Returns approximate row counts for every public-schema table.
CREATE OR REPLACE FUNCTION public.get_table_row_counts()
RETURNS TABLE(table_name text, row_count bigint)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  rec record;
  cnt bigint;
BEGIN
  FOR rec IN
    SELECT t.table_name
    FROM information_schema.tables t
    WHERE t.table_schema = 'public'
      AND t.table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('SELECT COUNT(*) FROM public.%I', rec.table_name) INTO cnt;
    table_name := rec.table_name;
    row_count := cnt;
    RETURN NEXT;
  END LOOP;
END;
$$;

-- Executes an arbitrary read-only SQL query and returns the result as JSON.
-- Used as a fallback by the backup discovery code. SECURITY DEFINER is safe
-- here because the function is only callable by the service role (Supabase
-- does not expose it to anon/authenticated by default).
CREATE OR REPLACE FUNCTION public.exec_sql(query text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  result jsonb;
BEGIN
  EXECUTE 'SELECT COALESCE(jsonb_agg(row_to_json(r)), ''[]''::jsonb) FROM (' || query || ') r'
    INTO result;
  RETURN result;
END;
$$;

-- Restrict exec_sql to service role only (defense in depth).
-- The anon/authenticated REVOKE is wrapped in a DO/EXCEPTION block because
-- those roles only exist in Supabase modes; on plain Postgres the REVOKE
-- would raise 42704 and abort the install.
REVOKE ALL ON FUNCTION public.exec_sql(text) FROM PUBLIC;
DO $$
BEGIN
  REVOKE ALL ON FUNCTION public.exec_sql(text) FROM anon, authenticated;
EXCEPTION
  WHEN undefined_object THEN NULL;
END $$;
`
