import { NextResponse } from 'next/server'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { z } from 'zod'
import { getAuthenticatedUser } from '@/lib/auth-helpers'
import { registry } from '@/lib/openapi/registry'
import { DEFAULT_SECURITY, InternalServerErrorResponse, UnauthorizedResponse } from '@/lib/openapi/common'

export const debugRole = 'unit-tests'

// Generated by `pnpm generate-test-report` (runs on predev/prebuild). Gitignored
// under lib/generated/, so it may be absent until the first generation — the
// route degrades gracefully rather than erroring.
const REPORT_PATH = path.join(process.cwd(), 'lib', 'generated', 'test-report.json')

// The report only changes when the process restarts (regenerated in predev),
// so cache the reshaped payload after the first successful read.
let cached: UnitTestReport | null = null

registry.registerPath({
  method: 'get',
  path: '/api/health/unit-tests',
  operationId: 'getHealthUnitTests',
  summary: 'Static unit-test report (pass/fail snapshot from the last `vitest` run)',
  tags: ['app'],
  security: DEFAULT_SECURITY,
  responses: {
    200: { description: 'Unit-test report snapshot', content: { 'application/json': { schema: z.any() } } },
    401: UnauthorizedResponse,
    500: InternalServerErrorResponse,
  },
})

// ── Shapes ──────────────────────────────────────────────────────────────────

interface RawAssertion {
  title?: string
  fullName?: string
  ancestorTitles?: string[]
  status?: string
  duration?: number
  failureMessages?: string[]
}
interface RawFile {
  name?: string
  status?: string
  message?: string
  startTime?: number
  endTime?: number
  assertionResults?: RawAssertion[]
}
interface RawReport {
  generatedAt?: string
  success?: boolean
  error?: string
  numTotalTests?: number
  numPassedTests?: number
  numFailedTests?: number
  numPendingTests?: number
  numTodoTests?: number
  startTime?: number
  testResults?: RawFile[]
}

interface TestEntry {
  title: string
  status: string
  durationMs: number
  failureMessage: string | null
}
interface FileEntry {
  name: string
  status: string
  passed: number
  failed: number
  skipped: number
  durationMs: number
  // File-level error (e.g. an import/collect failure) that produced no
  // individual test results. Null for normal files.
  message: string | null
  tests: TestEntry[]
}
interface UnitTestReport {
  ok: boolean
  error: string | null
  generatedAt: string | null
  totals: { total: number; passed: number; failed: number; skipped: number; passRate: number; durationMs: number }
  files: FileEntry[]
}

// ── Helpers ─────────────────────────────────────────────────────────────────

// Strip ANSI SGR color codes from failure text. The ESC is the \u001b escape
// (not a raw ESC byte) so an editor/formatter can't silently drop it.
// eslint-disable-next-line no-control-regex
const ANSI = /\u001b\[[0-9;]*m/g
const stripAnsi = (s: string): string => s.replace(ANSI, '')

function isSkipped(status: string | undefined): boolean {
  return status === 'skipped' || status === 'pending' || status === 'todo'
}

function reshape(raw: RawReport): UnitTestReport {
  const cwd = process.cwd()
  const files: FileEntry[] = (raw.testResults ?? []).map((f) => {
    const assertions = f.assertionResults ?? []
    let passed = 0
    let failed = 0
    let skipped = 0
    const tests: TestEntry[] = assertions.map((a) => {
      if (a.status === 'passed') passed++
      else if (a.status === 'failed') failed++
      else if (isSkipped(a.status)) skipped++
      const ancestors = (a.ancestorTitles ?? []).join(' › ')
      const title = a.fullName?.trim() || [ancestors, a.title].filter(Boolean).join(' › ') || '(unnamed test)'
      const failureMessage =
        a.status === 'failed' && a.failureMessages?.length ? stripAnsi(a.failureMessages[0]) : null
      return { title, status: a.status ?? 'unknown', durationMs: Math.round(a.duration ?? 0), failureMessage }
    })
    const durationMs =
      typeof f.endTime === 'number' && typeof f.startTime === 'number'
        ? Math.max(0, Math.round(f.endTime - f.startTime))
        : tests.reduce((sum, t) => sum + t.durationMs, 0)
    const name = f.name ? path.relative(cwd, f.name).replace(/\\/g, '/') : '(unknown file)'
    // A file can fail to even load (import/collect error): status 'failed' with
    // zero assertions. Mark it failed and surface its file-level message so it
    // isn't silently buried among the passing files.
    const status = failed > 0 || f.status === 'failed' ? 'failed' : f.status || (passed > 0 ? 'passed' : 'skipped')
    const message = failed === 0 && f.status === 'failed' && f.message ? stripAnsi(f.message) : null
    return { name, status, passed, failed, skipped, durationMs, message, tests }
  })

  // Sort failing files first (including load-error files with no failed
  // assertions), then alphabetically — surfaces problems at the top.
  files.sort(
    (a, b) => (b.status === 'failed' ? 1 : 0) - (a.status === 'failed' ? 1 : 0) || a.name.localeCompare(b.name)
  )

  const endTimes = (raw.testResults ?? [])
    .map((f) => f.endTime)
    .filter((n): n is number => typeof n === 'number')
  const wallMs =
    typeof raw.startTime === 'number' && endTimes.length > 0
      ? Math.max(0, Math.round(Math.max(...endTimes) - raw.startTime))
      : files.reduce((sum, f) => sum + f.durationMs, 0)

  const total = raw.numTotalTests ?? 0
  const passed = raw.numPassedTests ?? 0
  // Floor so a single failure can never round up to a green "100% passed".
  const passRate = total > 0 ? Math.floor((passed / total) * 100) : 0
  return {
    // `ok` means "we have a real report with tests" — NOT "all passed". A run
    // with failing tests must still render its breakdown, not the empty state.
    ok: total > 0,
    error: raw.error ?? null,
    generatedAt: raw.generatedAt ?? null,
    totals: {
      total,
      passed,
      failed: raw.numFailedTests ?? 0,
      skipped: (raw.numPendingTests ?? 0) + (raw.numTodoTests ?? 0),
      passRate,
      durationMs: wallMs,
    },
    files,
  }
}

const EMPTY = (error: string): UnitTestReport => ({
  ok: false,
  error,
  generatedAt: null,
  totals: { total: 0, passed: 0, failed: 0, skipped: 0, passRate: 0, durationMs: 0 },
  files: [],
})

// ── Handler ─────────────────────────────────────────────────────────────────

export async function GET() {
  const { user } = await getAuthenticatedUser()
  if (!user) {
    return NextResponse.json({ error: 'Authentication required' }, { status: 401 })
  }

  if (cached) return NextResponse.json(cached)

  let raw: string
  try {
    raw = await fs.readFile(REPORT_PATH, 'utf8')
  } catch {
    // Not generated yet — expected before the first predev/prebuild run.
    return NextResponse.json(
      EMPTY('Report not generated yet. Run `pnpm generate-test-report` (or restart the dev server).')
    )
  }

  try {
    const report = reshape(JSON.parse(raw) as RawReport)
    if (report.ok) cached = report // cache any real report (passing or failing)
    return NextResponse.json(report)
  } catch (err) {
    console.error('[health/unit-tests] Failed to parse report:', err)
    return NextResponse.json({ error: 'Failed to read unit-test report' }, { status: 500 })
  }
}
