import { pgTable, index, pgPolicy, foreignKey, uuid, text, timestamp, integer, date, boolean, numeric, jsonb } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"
import { user } from "@/lib/db/schema/core-schema"

export const tasks = pgTable("tasks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	title: text().notNull(),
	notes: text(),
	assignees: text().array().default([""]),
	dueDate: date("due_date"),
	subtasksCompleted: integer("subtasks_completed").default(0),
	subtasksTotal: integer("subtasks_total").default(0),
	status: text().default('Pending'),
	priority: text().default('Medium'),
	pinned: boolean().default(false),
	completed: boolean().default(false),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	orderIndex: integer("order_index").default(0),
	completionCount: integer("completion_count").default(0),
	userEmail: text("user_email"),
	userId: text("user_id").notNull(),
	impact: integer().default(3),
	severity: integer().default(3),
	timeliness: integer().default(3),
	effort: integer().default(3),
	strategicFit: integer("strategic_fit").default(3),
	priorityScore: numeric("priority_score", { precision: 10, scale:  4 }).default('0'),
	projectId: uuid("project_id"),
	monsterType: text("monster_type"),
	monsterColors: jsonb("monster_colors"),
	assignedAgentId: text("assigned_agent_id"),
}, (table) => [
	index("idx_ari_database_completed").using("btree", table.completed.asc().nullsLast().op("bool_ops")),
	index("idx_ari_database_completion_count").using("btree", table.completionCount.asc().nullsLast().op("int4_ops")),
	index("idx_ari_database_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamptz_ops")),
	index("idx_ari_database_order").using("btree", table.orderIndex.asc().nullsLast().op("int4_ops")),
	index("idx_ari_database_starred").using("btree", table.pinned.asc().nullsLast().op("bool_ops")),
	index("idx_ari_database_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("idx_tasks_monster_type").using("btree", table.monsterType.asc().nullsLast().op("text_ops")),
	index("idx_tasks_priority_score").using("btree", table.priorityScore.asc().nullsLast().op("numeric_ops")),
	index("idx_tasks_project_id").using("btree", table.projectId.asc().nullsLast().op("uuid_ops")),
	index("idx_tasks_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	index("idx_tasks_user_id_completed").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.completed.asc().nullsLast().op("bool_ops")),
	pgPolicy("tasks_rls_select", { as: "permissive", for: "select", to: ["public"], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
	pgPolicy("tasks_rls_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(user_id = (select current_setting('app.current_user_id')))` }),
	pgPolicy("tasks_rls_update", { as: "permissive", for: "update", to: ["public"], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
	pgPolicy("tasks_rls_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
]);

export const taskSubtasks = pgTable("task_subtasks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	taskId: uuid("task_id").notNull(),
	userId: text("user_id").notNull(),
	title: text().notNull(),
	completed: boolean().default(false).notNull(),
	orderIndex: integer("order_index").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_task_subtasks_task_id").using("btree", table.taskId.asc().nullsLast().op("uuid_ops")),
	index("idx_task_subtasks_user_id").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	index("idx_task_subtasks_user_task").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.taskId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
		columns: [table.taskId],
		foreignColumns: [tasks.id],
		name: "task_subtasks_task_id_fkey",
	}).onDelete("cascade"),
	foreignKey({
		columns: [table.userId],
		foreignColumns: [user.id],
		name: "task_subtasks_user_id_fkey",
	}).onDelete("cascade"),
	pgPolicy("task_subtasks_rls_select", { as: "permissive", for: "select", to: ["public"], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
	pgPolicy("task_subtasks_rls_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(user_id = (select current_setting('app.current_user_id')))` }),
	pgPolicy("task_subtasks_rls_update", { as: "permissive", for: "update", to: ["public"], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
	pgPolicy("task_subtasks_rls_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`(user_id = (select current_setting('app.current_user_id')))` }),
]);
