export { GeneralTab } from "./GeneralTab"
export { FontsTab } from "./FontsTab"
export { ThemesTab } from "./ThemesTab"
export { KeybindingsTab } from "./KeybindingsTab"
export { NotificationsTab } from "./NotificationsTab"
export { SecurityTab } from "./SecurityTab"
export { IntegrationsTab } from "./IntegrationsTab"
export { BackupsTab } from "./BackupsTab"
