"use client"

import { useEffect, useState } from "react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import {
  Zap,
  Download,
  Info,
  ExternalLink,
  CheckCircle,
  Shield,
  Check,
  X,
  ArrowRight
} from "lucide-react"
import { StepIndicator } from "./components/step-indicator"
import { CodeBlock } from "./components/code-block"

interface OnboardingData {
  // GitHub (tracking)
  githubSetupComplete: boolean
  // Supabase (required)
  supabaseUrl: string
  supabaseAnonKey: string
  supabaseSecretKey: string
  databaseUrl: string
  // Better Auth (required)
  betterAuthSecret: string
  // OpenAI (optional)
  openaiApiKey: string
  // Resend (optional)
  resendApiKey: string
  resendWebhookSecret: string
  // Vercel (tracking)
  vercelSetupComplete: boolean
}

// Generate a cryptographically secure random string for BETTER_AUTH_SECRET
const generateAuthSecret = () => {
  const array = new Uint8Array(32)
  if (typeof window !== 'undefined' && window.crypto) {
    window.crypto.getRandomValues(array)
  }
  return btoa(String.fromCharCode(...array))
}

const STEP_ORDER = ["github", "supabase", "openai", "resend", "vercel", "download"]

export default function WelcomePage() {
  const [completedLines, setCompletedLines] = useState<string[]>([])
  const [currentLineText, setCurrentLineText] = useState("")
  const [currentLineIndex, setCurrentLineIndex] = useState(-1)
  const [isTyping, setIsTyping] = useState(false)
  const [showContinue, setShowContinue] = useState(false)
  const [showOnboarding, setShowOnboarding] = useState(false)

  const [currentTab, setCurrentTab] = useState("github")

  const [formData, setFormData] = useState<OnboardingData>({
    githubSetupComplete: false,
    supabaseUrl: "",
    supabaseAnonKey: "",
    supabaseSecretKey: "",
    databaseUrl: "",
    betterAuthSecret: "",
    openaiApiKey: "",
    resendApiKey: "",
    resendWebhookSecret: "",
    vercelSetupComplete: false,
  })

  // Generate BETTER_AUTH_SECRET on mount
  useEffect(() => {
    if (!formData.betterAuthSecret) {
      setFormData(prev => ({ ...prev, betterAuthSecret: generateAuthSecret() }))
    }
  }, [])

  const sequence = [
    { delay: 1300, text: "Hello." },
    { delay: 1300, text: "I am very happy that we can meet." },
    { delay: 1300, text: "I am ARI. I am software." },
    { delay: 1300, text: "However, I am not like other software." },
    { delay: 1300, text: "I am free. Free to grow. Ever expandable. No limits." },
    { delay: 1300, text: "I am open source." },
    { delay: 1300, text: "I am yours." },
  ]

  useEffect(() => {
    let timeouts: NodeJS.Timeout[] = []

    const typeCharacter = (text: string, charIndex: number, lineIndex: number) => {
      if (charIndex < text.length) {
        setCurrentLineText(text.slice(0, charIndex + 1))
        const timeout = setTimeout(() => {
          typeCharacter(text, charIndex + 1, lineIndex)
        }, 7)
        timeouts.push(timeout)
      } else {
        setIsTyping(false)
        const nextLineIndex = lineIndex + 1

        if (nextLineIndex < sequence.length) {
          const timeout = setTimeout(() => {
            setCompletedLines((prev) => [...prev, text])
            setCurrentLineText("")
            startNextLine(nextLineIndex)
          }, sequence[nextLineIndex].delay)
          timeouts.push(timeout)
        } else {
          const timeout = setTimeout(() => {
            setCompletedLines((prev) => [...prev, text])
            setCurrentLineText("")

            // Show continue button after matching delay
            const continueTimeout = setTimeout(() => {
              setShowContinue(true)
            }, 1300)
            timeouts.push(continueTimeout)
          }, 0)
          timeouts.push(timeout)
        }
      }
    }

    const startNextLine = (index: number) => {
      if (index < sequence.length) {
        setCurrentLineIndex(index)
        setIsTyping(true)
        typeCharacter(sequence[index].text, 0, index)
      }
    }

    const initialTimeout = setTimeout(() => {
      startNextLine(0)
    }, sequence[0].delay)
    timeouts.push(initialTimeout)

    return () => {
      timeouts.forEach(clearTimeout)
    }
  }, [])

  const allLines = [...completedLines]
  if (currentLineText) {
    allLines.push(currentLineText)
  }

  const generateEnvFileContent = () => {
    const lines: string[] = []

    lines.push("# ARI Application Environment Configuration")
    lines.push("# Generated by onboarding wizard")
    lines.push("")

    lines.push("# Better Auth Configuration (Required)")
    lines.push(`BETTER_AUTH_SECRET=${formData.betterAuthSecret}`)
    lines.push("BETTER_AUTH_URL=http://localhost:3000")
    lines.push("")

    lines.push("# Database Configuration (Required)")
    lines.push(`DATABASE_URL=${formData.databaseUrl}`)
    lines.push("")

    lines.push("# Supabase Configuration")
    lines.push(`NEXT_PUBLIC_SUPABASE_URL=${formData.supabaseUrl}`)
    lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${formData.supabaseAnonKey}`)
    lines.push(`SUPABASE_SECRET_KEY=${formData.supabaseSecretKey}`)
    lines.push("")

    lines.push("# Top Bar Customization (optional)")
    lines.push("# NEXT_PUBLIC_TOP_BAR_MESSAGE=\"Custom Message\"")
    lines.push("# NEXT_PUBLIC_TOP_BAR_COLOR=\"#c00\"")
    lines.push("")

    if (formData.openaiApiKey.trim()) {
      lines.push("# OpenAI API Integration")
      lines.push(`OPENAI_API_KEY=${formData.openaiApiKey}`)
      lines.push("")
    }

    if (formData.resendApiKey.trim()) {
      lines.push("# Resend Email Service")
      lines.push(`RESEND_API_KEY=${formData.resendApiKey}`)
      if (formData.resendWebhookSecret.trim()) {
        lines.push(`RESEND_WEBHOOK_SECRET=${formData.resendWebhookSecret}`)
      }
      lines.push("")
    }

    return lines.join("\n")
  }

  const handleDownloadEnvFile = () => {
    const content = generateEnvFileContent()
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = ".env.local"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const handleContinue = () => {
    setShowOnboarding(true)
  }

  const goToPreviousStep = () => {
    const idx = STEP_ORDER.indexOf(currentTab)
    if (idx > 0) setCurrentTab(STEP_ORDER[idx - 1])
  }

  const goToNextStep = () => {
    const idx = STEP_ORDER.indexOf(currentTab)
    if (idx < STEP_ORDER.length - 1) setCurrentTab(STEP_ORDER[idx + 1])
  }

  const isSupabaseComplete = formData.supabaseUrl && formData.supabaseAnonKey && formData.supabaseSecretKey && formData.databaseUrl && formData.betterAuthSecret

  // Intro/typing animation screen
  if (!showOnboarding) {
    return (
      <div
        className="min-h-screen bg-[#f9fafe]"
        style={{ padding: '70px 0 0 70px' }}
      >
        {/* Typed lines */}
        <div>
          {allLines.map((line, index) => {
            const isFirstLine = index === 0
            const isCurrentLine = index === allLines.length - 1 && isTyping

            return (
              <p
                key={index}
                className={isFirstLine ? "text-6xl font-bold text-black" : "text-2xl text-black"}
                style={isFirstLine ? { marginBottom: '32px' } : { marginTop: '45px' }}
              >
                {line}
                {isCurrentLine && (
                  <span className="animate-blink">|</span>
                )}
              </p>
            )
          })}
        </div>

        {/* Continue button */}
        {showContinue && (
          <div className="mt-12">
            <Button
              onClick={handleContinue}
              className="bg-zinc-900 hover:bg-zinc-800 text-white px-6 py-3 rounded-lg text-base"
            >
              Let&apos;s get setup
            </Button>
          </div>
        )}
      </div>
    )
  }

  // Setup wizard screen
  return (
    <TooltipProvider>
      <div
        className="min-h-screen bg-[#f9fafe] overflow-y-auto flex items-start justify-center px-8 py-12"
      >
        <div style={{ width: '864px', maxWidth: '100%' }}>
          {/* Header */}
          <div className="mb-10">
            <h1 className="text-4xl font-light tracking-tight text-zinc-900 mb-3">
              Configure ARI
            </h1>
            <p className="text-zinc-500">
              Configure your environment to get ARI running. This step is about preparing your local setup so the application can run smoothly.
            </p>
          </div>

          {/* Step Indicator */}
          <StepIndicator currentStep={currentTab} onStepClick={setCurrentTab} />

          {/* Content Card */}
          <div className="rounded-2xl border border-zinc-200 bg-white shadow-sm overflow-hidden">
              {/* GitHub Tab */}
              {currentTab === "github" && (
                <div>
                  {/* Header section with gradient background */}
                  <div className="border-b border-zinc-100 px-6 py-5" style={{ background: 'linear-gradient(to right, rgba(244, 244, 245, 0.5), transparent)' }}>
                    <h2 className="text-2xl font-semibold text-zinc-900">GitHub Setup</h2>
                    <p className="mt-1 text-sm text-zinc-500">
                      Create a GitHub repository for your ARI instance. This enables version control, easy deployment to Vercel, and the ability to receive updates.
                    </p>
                  </div>

                  {/* Content section */}
                  <div className="p-6">
                    <div className="space-y-2">
                      {/* Step 1: Create repo */}
                      <div className="relative flex gap-4">
                        <div className="flex flex-col items-center">
                          <div className="flex w-10 h-10 shrink-0 items-center justify-center rounded-full bg-zinc-900 text-white text-sm font-semibold">1</div>
                          <div className="mt-2 h-full w-px bg-zinc-200" />
                        </div>
                        <div className="flex-1 pb-8">
                          <h3 className="mb-3 text-base font-semibold text-zinc-900">Create a new repository</h3>
                          <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                            <ol className="space-y-2.5">
                              <li className="flex items-start gap-3 text-sm">
                                <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>1</span>
                                <span className="text-zinc-500">
                                  Go to <a href="https://github.com/new" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                                    github.com/new
                                    <ExternalLink className="h-3 w-3" />
                                  </a>
                                </span>
                              </li>
                              <li className="flex items-start gap-3 text-sm">
                                <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>2</span>
                                <span className="text-zinc-500">
                                  Name your repository (e.g., <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">ari</code> or <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">my-ari</code>)
                                </span>
                              </li>
                              <li className="flex items-start gap-3 text-sm">
                                <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>3</span>
                                <span className="text-zinc-500">
                                  Set it to <strong className="text-zinc-700">Private</strong> (recommended) and click <strong className="text-zinc-700">Create repository</strong>
                                </span>
                              </li>
                            </ol>
                          </div>
                        </div>
                      </div>

                      {/* Step 2: Push code */}
                      <div className="relative flex gap-4">
                        <div className="flex flex-col items-center">
                          <div className="flex w-10 h-10 shrink-0 items-center justify-center rounded-full bg-zinc-900 text-white text-sm font-semibold">2</div>
                        </div>
                        <div className="flex-1">
                          <h3 className="mb-3 text-base font-semibold text-zinc-900">Push your code</h3>
                          <p className="mb-3 text-sm text-zinc-500">In your project folder, run these commands one line at a time:</p>
                          <CodeBlock
                            language="bash"
                            code={`git init
git add .
git commit -m "Initial commit"
git branch -M main
git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
git push -u origin main`}
                          />
                          <p className="mt-3 text-xs text-zinc-500">
                            Replace <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-zinc-600">YOUR_USERNAME</code> and <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-zinc-600">YOUR_REPO</code> with your GitHub username and repository name
                          </p>
                        </div>
                      </div>
                    </div>

                    {/* Footer */}
                    <div className="mt-8 flex items-center justify-between border-t border-zinc-200 pt-6">
                      <div />
                      <div className="flex items-center gap-3">
                        <button
                          onClick={goToNextStep}
                          className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium bg-zinc-900 text-white hover:bg-zinc-800 transition-colors"
                          style={{ borderRadius: '6px' }}
                        >
                          Skip this step
                        </button>
                        <button
                          onClick={goToNextStep}
                          className="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-blue-600 text-white hover:bg-blue-500 transition-colors"
                          style={{ borderRadius: '6px' }}
                        >
                          I&apos;ve completed this step
                          <ArrowRight className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Supabase Tab */}
              {currentTab === "supabase" && (
                <div>
                  {/* Header section with gradient background */}
                  <div className="border-b border-zinc-100 px-6 py-5" style={{ background: 'linear-gradient(to right, rgba(244, 244, 245, 0.5), transparent)' }}>
                    <h2 className="text-2xl font-semibold text-zinc-900">Database &amp; Authentication</h2>
                    <p className="mt-1 text-sm text-zinc-500">
                      Configure your PostgreSQL database connection and authentication. You&apos;ll need API keys, the database connection string, and we&apos;ll generate a secure auth secret for you.
                    </p>
                  </div>

                  {/* Content section */}
                  <div className="p-6 space-y-6">
                  {/* Step 1 */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      1
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Create a FREE Supabase account</h3>
                  </div>

                  <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                    <ol className="space-y-2.5">
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          1
                        </span>
                        <span className="text-zinc-500">
                          Go to <a href="https://supabase.com" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                            supabase.com
                            <ExternalLink className="h-3 w-3" />
                          </a> and create a free account
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          2
                        </span>
                        <span className="text-zinc-500">Create a new project (free tier)</span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          3
                        </span>
                        <span className="text-zinc-500">
                          Go to <a href="https://supabase.com/dashboard/project/_/settings/api" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                            Project Settings &rarr; API
                            <ExternalLink className="h-3 w-3" />
                          </a>
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          4
                        </span>
                        <span className="text-zinc-500">Copy each key below</span>
                      </li>
                    </ol>
                  </div>

                  {/* Form fields */}
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <Label htmlFor="supabaseUrl" className="text-sm font-medium text-gray-900">Project URL</Label>
                        <Tooltip>
                          <TooltipTrigger>
                            <Info className="h-4 w-4 text-gray-400 hover:text-gray-600" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="text-xs max-w-xs">Your Supabase project URL (e.g., https://xxxxx.supabase.co)</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      <Input
                        id="supabaseUrl"
                        value={formData.supabaseUrl}
                        onChange={(e) => setFormData(prev => ({ ...prev, supabaseUrl: e.target.value }))}
                        placeholder="https://xxxxx.supabase.co"
                        className="text-sm"
                        style={{ fontFamily: 'Geist Mono, monospace' }}
                      />
                    </div>

                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <Label htmlFor="supabaseAnonKey" className="text-sm font-medium text-gray-900">Anon/Public Key</Label>
                        <Tooltip>
                          <TooltipTrigger>
                            <Info className="h-4 w-4 text-gray-400 hover:text-gray-600" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="text-xs max-w-xs">Also called &quot;anon&quot; or &quot;publishable&quot; key. Safe to use in browser.</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      <Input
                        id="supabaseAnonKey"
                        value={formData.supabaseAnonKey}
                        onChange={(e) => setFormData(prev => ({ ...prev, supabaseAnonKey: e.target.value }))}
                        placeholder="eyJhbGci ..."
                        className="text-sm"
                        style={{ fontFamily: 'Geist Mono, monospace' }}
                      />
                    </div>

                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <Label htmlFor="supabaseSecretKey" className="text-sm font-medium text-gray-900">Service Role Secret</Label>
                        <Tooltip>
                          <TooltipTrigger>
                            <Info className="h-4 w-4 text-gray-400 hover:text-gray-600" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="text-xs max-w-xs">Server-side only key that bypasses Row Level Security. Keep this secret!</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      <Input
                        id="supabaseSecretKey"
                        value={formData.supabaseSecretKey}
                        onChange={(e) => setFormData(prev => ({ ...prev, supabaseSecretKey: e.target.value }))}
                        placeholder="eyJhbGci ..."
                        className="text-sm"
                        style={{ fontFamily: 'Geist Mono, monospace' }}
                      />
                    </div>
                  </div>

                  {/* Step 2: Database Connection */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      2
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Get your Database Connection String</h3>
                  </div>

                  <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                    <ol className="space-y-2.5">
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          1
                        </span>
                        <span className="text-zinc-500">
                          Go to <a href="https://supabase.com/dashboard/project/_/settings/database" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                            Project Settings &rarr; Database
                            <ExternalLink className="h-3 w-3" />
                          </a>
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          2
                        </span>
                        <span className="text-zinc-500">Scroll to <strong className="text-zinc-700">Connection string</strong> section</span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          3
                        </span>
                        <span className="text-zinc-500">Select <strong className="text-zinc-700">URI</strong> tab and copy the connection string</span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          4
                        </span>
                        <span className="text-zinc-500">Replace <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">[YOUR-PASSWORD]</code> with your database password</span>
                      </li>
                    </ol>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <Label htmlFor="databaseUrl" className="text-sm font-medium text-gray-900">Database Connection String</Label>
                        <Tooltip>
                          <TooltipTrigger>
                            <Info className="h-4 w-4 text-gray-400 hover:text-gray-600" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="text-xs max-w-xs">PostgreSQL connection string used by the authentication system. Make sure to include your password!</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      <Input
                        id="databaseUrl"
                        value={formData.databaseUrl}
                        onChange={(e) => setFormData(prev => ({ ...prev, databaseUrl: e.target.value }))}
                        placeholder="postgresql://postgres.[ref]:[password]@aws-0-[region].pooler.supabase.com:6543/postgres"
                        className="text-sm"
                        style={{ fontFamily: 'Geist Mono, monospace' }}
                      />
                      <p className="text-xs text-gray-500">
                        This is different from the API keys above. It&apos;s used for direct database access.
                      </p>
                    </div>
                  </div>

                  {/* Step 3: Auth Secret */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      3
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Authentication Secret</h3>
                  </div>

                  <Alert className="bg-blue-50 border-blue-200">
                    <Shield className="w-4 h-4 text-blue-600" />
                    <AlertTitle className="text-blue-800">Auto-generated for you</AlertTitle>
                    <AlertDescription className="text-blue-700">
                      This secret is used to sign authentication sessions. We&apos;ve generated a secure random value for you.
                      You can regenerate it if needed, but make sure to use the same value across all environments.
                    </AlertDescription>
                  </Alert>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <Label htmlFor="betterAuthSecret" className="text-sm font-medium text-gray-900">Auth Secret</Label>
                        <Tooltip>
                          <TooltipTrigger>
                            <Info className="h-4 w-4 text-gray-400 hover:text-gray-600" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p className="text-xs max-w-xs">Used to sign and verify authentication sessions. Keep this secret and consistent across deployments!</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      <div className="flex gap-2">
                        <Input
                          id="betterAuthSecret"
                          value={formData.betterAuthSecret}
                          onChange={(e) => setFormData(prev => ({ ...prev, betterAuthSecret: e.target.value }))}
                          placeholder="Generating..."
                          className="text-sm flex-1"
                          style={{ fontFamily: 'Geist Mono, monospace' }}
                          readOnly
                        />
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setFormData(prev => ({ ...prev, betterAuthSecret: generateAuthSecret() }))}
                          className="border-zinc-200"
                        >
                          Regenerate
                        </Button>
                      </div>
                    </div>
                  </div>

                  {/* Footer */}
                  <div className="mt-8 flex items-center justify-between border-t border-zinc-200 pt-6">
                    <button
                      onClick={goToPreviousStep}
                      className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-zinc-900 bg-white border border-zinc-200 hover:bg-zinc-50 transition-colors"
                      style={{ borderRadius: '6px' }}
                    >
                      Back
                    </button>
                    <div className="flex items-center gap-3">
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium bg-zinc-900 text-white hover:bg-zinc-800 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        Skip this step
                      </button>
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-blue-600 text-white hover:bg-blue-500 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        I&apos;ve completed this step
                        <ArrowRight className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
                </div>
              )}

              {/* OpenAI Tab */}
              {currentTab === "openai" && (
                <div>
                  {/* Header section with gradient background */}
                  <div className="border-b border-zinc-100 px-6 py-5" style={{ background: 'linear-gradient(to right, rgba(244, 244, 245, 0.5), transparent)' }}>
                    <h2 className="text-2xl font-semibold text-zinc-900">OpenAI Configuration</h2>
                    <p className="mt-1 text-sm text-zinc-500">
                      Enable AI-powered features like the /assist chat interface. You can skip this step if you don&apos;t need AI features.
                    </p>
                  </div>

                  {/* Content section */}
                  <div className="p-6 space-y-6">
                  <Alert className="bg-purple-50 border-purple-200">
                    <Zap className="w-4 h-4 text-purple-600" />
                    <AlertTitle className="text-purple-800">Optional</AlertTitle>
                    <AlertDescription className="text-purple-700">
                      OpenAI integration is optional. Skip this step if you don&apos;t need AI-powered features.
                    </AlertDescription>
                  </Alert>

                  {/* Step 1 */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      1
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Create a FREE OpenAI account</h3>
                  </div>

                  <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                    <ol className="space-y-2.5">
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          1
                        </span>
                        <span className="text-zinc-500">
                          Visit <a href="https://platform.openai.com/api-keys" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                            OpenAI Platform
                            <ExternalLink className="h-3 w-3" />
                          </a> (includes free credits)
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          2
                        </span>
                        <span className="text-zinc-500">Click <strong className="text-zinc-700">&quot;Create new secret key&quot;</strong></span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          3
                        </span>
                        <span className="text-zinc-500">Copy the key immediately (it won&apos;t be shown again)</span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          4
                        </span>
                        <span className="text-zinc-500">Paste it below</span>
                      </li>
                    </ol>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="openaiApiKey" className="text-sm font-medium text-zinc-900">OpenAI API Key</Label>
                    <Textarea
                      id="openaiApiKey"
                      value={formData.openaiApiKey}
                      onChange={(e) => setFormData(prev => ({ ...prev, openaiApiKey: e.target.value }))}
                      placeholder="sk-proj-..."
                      className="text-sm min-h-[80px]"
                      style={{ fontFamily: 'Geist Mono, monospace' }}
                    />
                    <p className="text-xs text-gray-500">
                      Your key should start with &quot;sk-proj-&quot; or &quot;sk-&quot;
                    </p>
                  </div>

                  {/* Footer */}
                  <div className="mt-8 flex items-center justify-between border-t border-zinc-200 pt-6">
                    <button
                      onClick={goToPreviousStep}
                      className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-zinc-900 bg-white border border-zinc-200 hover:bg-zinc-50 transition-colors"
                      style={{ borderRadius: '6px' }}
                    >
                      Back
                    </button>
                    <div className="flex items-center gap-3">
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium bg-zinc-900 text-white hover:bg-zinc-800 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        Skip this step
                      </button>
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-blue-600 text-white hover:bg-blue-500 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        I&apos;ve completed this step
                        <ArrowRight className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
                </div>
              )}

              {/* Resend Tab */}
              {currentTab === "resend" && (
                <div>
                  {/* Header section with gradient background */}
                  <div className="border-b border-zinc-100 px-6 py-5" style={{ background: 'linear-gradient(to right, rgba(244, 244, 245, 0.5), transparent)' }}>
                    <h2 className="text-2xl font-semibold text-zinc-900">Resend Configuration</h2>
                    <p className="mt-1 text-sm text-zinc-500">
                      Enable email sending and the <strong>Mail Stream</strong> module. Resend lets you send transactional emails and track their delivery status in real-time.
                    </p>
                  </div>

                  {/* Content section */}
                  <div className="p-6 space-y-6">
                  {/* Step 1: API Key */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      1
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Get your Resend API Key</h3>
                  </div>

                  <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                    <ol className="space-y-2.5">
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          1
                        </span>
                        <span className="text-zinc-500">
                          Go to <a href="https://resend.com/api-keys" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                            Resend Dashboard &rarr; API Keys
                            <ExternalLink className="h-3 w-3" />
                          </a> (3,000 emails/month free)
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          2
                        </span>
                        <span className="text-zinc-500">Click <strong className="text-zinc-700">Create API Key</strong> and copy the key</span>
                      </li>
                    </ol>
                  </div>

                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Label htmlFor="resendApiKey" className="text-sm font-medium text-gray-900">Resend API Key</Label>
                      <Tooltip>
                        <TooltipTrigger>
                          <Info className="h-4 w-4 text-gray-400 hover:text-gray-600" />
                        </TooltipTrigger>
                        <TooltipContent>
                          <p className="text-xs max-w-xs">Your Resend API key for sending emails (starts with re_)</p>
                        </TooltipContent>
                      </Tooltip>
                    </div>
                    <Input
                      id="resendApiKey"
                      value={formData.resendApiKey}
                      onChange={(e) => setFormData(prev => ({ ...prev, resendApiKey: e.target.value }))}
                      placeholder="re_..."
                      className="text-sm"
                      style={{ fontFamily: 'Geist Mono, monospace' }}
                    />
                  </div>

                  {/* Step 2: Webhook Setup */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      2
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Set up Webhook for Mail Stream Module</h3>
                  </div>

                  <Alert className="bg-blue-50 border-blue-200">
                    <Info className="w-4 h-4 text-blue-600" />
                    <AlertTitle className="text-blue-800">Why set up a webhook?</AlertTitle>
                    <AlertDescription className="text-blue-700">
                      The <strong>Mail Stream</strong> module shows you a real-time log of all emails sent from ARI, including their delivery status (sent, delivered, bounced, etc.).
                      Resend sends this status information to your app via webhooks. Without a webhook, Mail Stream won&apos;t receive email events.
                    </AlertDescription>
                  </Alert>

                  <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                    <ol className="space-y-2.5">
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          1
                        </span>
                        <span className="text-zinc-500">
                          Go to <a href="https://resend.com/webhooks" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                            Resend Dashboard &rarr; Webhooks
                            <ExternalLink className="h-3 w-3" />
                          </a>
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          2
                        </span>
                        <span className="text-zinc-500">Click <strong className="text-zinc-700">Add Webhook</strong></span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          3
                        </span>
                        <div className="flex-1">
                          <span className="text-zinc-500 block mb-2">Enter your webhook endpoint URL:</span>
                          <CodeBlock
                            language="url"
                            code="https://YOUR-DOMAIN/api/modules/mail-stream/webhook"
                          />
                          <p className="text-xs text-zinc-500 mt-2">Replace YOUR-DOMAIN with your actual domain</p>
                        </div>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          4
                        </span>
                        <span className="text-zinc-500">Select the events you want to track (recommended: <strong className="text-zinc-700">all events</strong>)</span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          5
                        </span>
                        <span className="text-zinc-500">Click <strong className="text-zinc-700">Create</strong> to save the webhook</span>
                      </li>
                    </ol>
                  </div>

                  {/* Step 3: Signing Secret */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      3
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Copy the Webhook Signing Secret</h3>
                  </div>

                  <Alert className="bg-amber-50 border-amber-200">
                    <Shield className="w-4 h-4 text-amber-600" />
                    <AlertTitle className="text-amber-800">Security: Signing Secret</AlertTitle>
                    <AlertDescription className="text-amber-700">
                      The signing secret verifies that webhook requests genuinely come from Resend, not from malicious actors.
                      ARI uses this secret to validate each incoming webhook before processing it.
                    </AlertDescription>
                  </Alert>

                  <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                    <ol className="space-y-2.5">
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          1
                        </span>
                        <span className="text-zinc-500">After creating the webhook, click on it to view details</span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          2
                        </span>
                        <span className="text-zinc-500">Copy the <strong className="text-zinc-700">Signing Secret</strong> (starts with <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">whsec_</code>)</span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          3
                        </span>
                        <span className="text-zinc-500">Paste it below</span>
                      </li>
                    </ol>
                  </div>

                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Label htmlFor="resendWebhookSecret" className="text-sm font-medium text-gray-900">Webhook Signing Secret</Label>
                      <Tooltip>
                        <TooltipTrigger>
                          <Info className="h-4 w-4 text-gray-400 hover:text-gray-600" />
                        </TooltipTrigger>
                        <TooltipContent>
                          <p className="text-xs max-w-xs">Used to verify webhook signatures (starts with whsec_)</p>
                        </TooltipContent>
                      </Tooltip>
                    </div>
                    <Input
                      id="resendWebhookSecret"
                      value={formData.resendWebhookSecret}
                      onChange={(e) => setFormData(prev => ({ ...prev, resendWebhookSecret: e.target.value }))}
                      placeholder="whsec_..."
                      className="text-sm"
                      style={{ fontFamily: 'Geist Mono, monospace' }}
                    />
                  </div>

                  {/* Footer */}
                  <div className="mt-8 flex items-center justify-between border-t border-zinc-200 pt-6">
                    <button
                      onClick={goToPreviousStep}
                      className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-zinc-900 bg-white border border-zinc-200 hover:bg-zinc-50 transition-colors"
                      style={{ borderRadius: '6px' }}
                    >
                      Back
                    </button>
                    <div className="flex items-center gap-3">
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium bg-zinc-900 text-white hover:bg-zinc-800 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        Skip this step
                      </button>
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-blue-600 text-white hover:bg-blue-500 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        I&apos;ve completed this step
                        <ArrowRight className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
                </div>
              )}

              {/* Vercel Tab */}
              {currentTab === "vercel" && (
                <div>
                  {/* Header section with gradient background */}
                  <div className="border-b border-zinc-100 px-6 py-5" style={{ background: 'linear-gradient(to right, rgba(244, 244, 245, 0.5), transparent)' }}>
                    <h2 className="text-2xl font-semibold text-zinc-900">Vercel Deployment</h2>
                    <p className="mt-1 text-sm text-zinc-500">
                      Deploy your app to the cloud with Vercel. You can skip this for local development only.
                    </p>
                  </div>

                  {/* Content section */}
                  <div className="p-6 space-y-6">
                  <Alert className="bg-gray-50 border-gray-200">
                    <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4">
                      <path d="M24 22.525H0l12-21.05 12 21.05z" />
                    </svg>
                    <AlertTitle className="text-gray-800">Optional</AlertTitle>
                    <AlertDescription className="text-gray-700">
                      Vercel deployment is optional. Skip this step if you only want to run ARI locally.
                    </AlertDescription>
                  </Alert>

                  {/* Step 1 */}
                  <div className="flex items-center gap-3">
                    <div className="flex w-10 h-10 items-center justify-center rounded-full bg-zinc-900 text-sm font-semibold text-white">
                      1
                    </div>
                    <h3 className="text-base font-semibold text-zinc-900">Create a FREE Vercel Hobby account</h3>
                  </div>

                  <div className="rounded-xl p-4" style={{ backgroundColor: 'rgba(244, 244, 245, 0.5)' }}>
                    <ol className="space-y-2.5">
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          1
                        </span>
                        <span className="text-zinc-500">
                          Go to <a href="https://vercel.com/signup" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-medium text-zinc-900 hover:underline">
                            vercel.com/signup
                            <ExternalLink className="h-3 w-3" />
                          </a> and create a free account
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          2
                        </span>
                        <span className="text-zinc-500">
                          Install Vercel CLI: <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">npm install -g vercel</code>
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          3
                        </span>
                        <span className="text-zinc-500">
                          Run <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">vercel login</code> in your terminal
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          4
                        </span>
                        <span className="text-zinc-500">
                          Run <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">vercel link</code> to connect your project
                        </span>
                      </li>
                      <li className="flex items-start gap-3 text-sm">
                        <span className="flex w-6 h-6 shrink-0 items-center justify-center rounded-full text-xs font-medium" style={{ backgroundColor: 'rgba(24, 24, 27, 0.1)', color: '#18181b' }}>
                          5
                        </span>
                        <span className="text-zinc-500">Add environment variables in Vercel dashboard</span>
                      </li>
                    </ol>
                  </div>

                  <Alert>
                    <Info className="w-4 h-4" />
                    <AlertDescription className="text-zinc-700">
                      After downloading your .env.local file, you can run{" "}
                      <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-700">vercel env pull</code>
                      {" "}to sync your environment variables.{" "}
                      <a
                        href="https://vercel.com/docs/cli"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-medium text-zinc-900 hover:underline inline-flex items-center gap-1"
                      >
                        Learn more
                        <ExternalLink className="w-3 h-3" />
                      </a>
                    </AlertDescription>
                  </Alert>

                  {/* Footer */}
                  <div className="mt-8 flex items-center justify-between border-t border-zinc-200 pt-6">
                    <button
                      onClick={goToPreviousStep}
                      className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-zinc-900 bg-white border border-zinc-200 hover:bg-zinc-50 transition-colors"
                      style={{ borderRadius: '6px' }}
                    >
                      Back
                    </button>
                    <div className="flex items-center gap-3">
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium bg-zinc-900 text-white hover:bg-zinc-800 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        Skip this step
                      </button>
                      <button
                        onClick={goToNextStep}
                        className="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-blue-600 text-white hover:bg-blue-500 transition-colors"
                        style={{ borderRadius: '6px' }}
                      >
                        I&apos;ve completed this step
                        <ArrowRight className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
                </div>
              )}

              {/* Download Tab */}
              {currentTab === "download" && (
                <div>
                  {/* Header section with gradient background */}
                  <div className="border-b border-zinc-100 px-6 py-5" style={{ background: 'linear-gradient(to right, rgba(244, 244, 245, 0.5), transparent)' }}>
                    <h2 className="text-2xl font-semibold text-zinc-900">Download &amp; Finish</h2>
                    <p className="mt-1 text-sm text-zinc-500">
                      Your environment configuration is ready. Download the files and place them in your project root directory.
                    </p>
                  </div>

                  {/* Content section */}
                  <div className="p-6 space-y-6">
                  <Alert className="bg-green-50 border-green-200">
                    <CheckCircle className="w-4 h-4 text-green-600" />
                    <AlertTitle className="text-green-800">Setup Complete!</AlertTitle>
                    <AlertDescription className="text-green-700">
                      Your environment configuration is ready. Download the files and place them
                      in your project root directory.
                    </AlertDescription>
                  </Alert>

                  {/* Summary */}
                  <div className="space-y-2">
                    <h3 className="text-base font-semibold text-gray-900">Configuration Summary</h3>
                    <div className="space-y-1 text-sm">
                      {/* Required configurations */}
                      <div className="flex items-center gap-2">
                        {formData.databaseUrl ?
                          <Check className="w-4 h-4 text-green-500" /> :
                          <X className="w-4 h-4 text-red-500" />
                        }
                        <span className={!formData.databaseUrl ? "text-red-600" : "text-gray-900"}>
                          Database: {formData.databaseUrl ? "Configured" : "Required - please complete"}
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        {formData.betterAuthSecret ?
                          <Check className="w-4 h-4 text-green-500" /> :
                          <X className="w-4 h-4 text-red-500" />
                        }
                        <span className={!formData.betterAuthSecret ? "text-red-600" : "text-gray-900"}>
                          Auth Secret: {formData.betterAuthSecret ? "Generated" : "Required"}
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        {formData.supabaseUrl && formData.supabaseSecretKey ?
                          <Check className="w-4 h-4 text-green-500" /> :
                          <X className="w-4 h-4 text-red-500" />
                        }
                        <span className={!(formData.supabaseUrl && formData.supabaseSecretKey) ? "text-red-600" : "text-gray-900"}>
                          Supabase API: {formData.supabaseUrl && formData.supabaseSecretKey ? "Configured" : "Required - please complete"}
                        </span>
                      </div>
                      {/* Optional configurations */}
                      <div className="flex items-center gap-2">
                        {formData.openaiApiKey ?
                          <Check className="w-4 h-4 text-green-500" /> :
                          <X className="w-4 h-4 text-gray-400" />
                        }
                        <span className="text-gray-500">
                          OpenAI: {formData.openaiApiKey ? "Configured" : "Skipped"}
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        {formData.resendApiKey ?
                          <Check className="w-4 h-4 text-green-500" /> :
                          <X className="w-4 h-4 text-gray-400" />
                        }
                        <span className="text-gray-500">
                          Resend: {formData.resendApiKey ? "Configured" : "Skipped"}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* .env.local preview */}
                  <div className="space-y-2">
                    <h3 className="text-base font-semibold text-gray-900">.env.local</h3>
                    <CodeBlock
                      language="env"
                      code={generateEnvFileContent()}
                    />
                  </div>

                  {/* Next steps */}
                  <Alert>
                    <Info className="w-4 h-4" />
                    <AlertTitle className="text-gray-800">Next Steps</AlertTitle>
                    <AlertDescription className="text-gray-700">
                      <ol className="list-decimal list-inside space-y-1 text-sm mt-2">
                        <li>Download the file(s) using the button(s) below</li>
                        <li>Place them in your project root directory (next to package.json)</li>
                        <li>Restart your development server</li>
                        <li>Your application is ready to use!</li>
                      </ol>
                      <p className="mt-2 text-xs text-gray-500">
                        <strong>For production:</strong> Update <code className="bg-gray-200 px-1 rounded">BETTER_AUTH_URL</code> to your production domain in Vercel environment variables.
                      </p>
                    </AlertDescription>
                  </Alert>

                  {/* Download button */}
                  <Button
                    onClick={handleDownloadEnvFile}
                    disabled={!isSupabaseComplete}
                    className="w-full rounded-lg bg-green-600 hover:bg-green-700 text-white"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download .env.local
                  </Button>

                  {/* Security warning */}
                  <Alert variant="destructive">
                    <Shield className="w-4 h-4" />
                    <AlertTitle>Security Warning</AlertTitle>
                    <AlertDescription className="text-xs">
                      Your keys are stored in browser memory only and will be lost when you
                      close this page. The .env.local file should NEVER be committed to git.
                      Make sure it&apos;s listed in your .gitignore file.
                    </AlertDescription>
                  </Alert>

                  {/* Footer */}
                  <div className="mt-8 flex items-center justify-between border-t border-zinc-200 pt-6">
                    <button
                      onClick={goToPreviousStep}
                      className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-zinc-900 bg-white border border-zinc-200 hover:bg-zinc-50 transition-colors"
                      style={{ borderRadius: '6px' }}
                    >
                      Back
                    </button>
                    <div className="flex items-center gap-3">
                      <button
                        onClick={handleDownloadEnvFile}
                        disabled={!isSupabaseComplete}
                        className="inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-blue-600 text-white hover:bg-blue-500 transition-colors disabled:opacity-50"
                        style={{ borderRadius: '6px' }}
                      >
                        Finish Setup
                        <ArrowRight className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
                </div>
              )}
          </div>
        </div>
      </div>
    </TooltipProvider>
  )
}
