/**
 * Regenerate Module Registry
 *
 * Programmatically regenerates the module-pages-registry.ts file.
 * This ensures the registry is always up-to-date when modules are discovered.
 *
 * Server-side only.
 */

import { readdir, readFile, writeFile, mkdir } from 'fs/promises'
import { join, dirname } from 'path'
import { existsSync } from 'fs'

const MODULE_DIRECTORIES = ['modules-custom', 'modules-core'] as const
const OUTPUT_FILE = join(process.cwd(), 'lib/generated/module-pages-registry.ts')

interface ModuleInfo {
  id: string
  dirName: string
  folder: string
}

/**
 * Scan a single modules directory
 */
async function scanModulesDirectory(dirName: string): Promise<ModuleInfo[]> {
  const modules: ModuleInfo[] = []
  const modulesDir = join(process.cwd(), dirName)

  if (!existsSync(modulesDir)) {
    return modules
  }

  try {
    const entries = await readdir(modulesDir, { withFileTypes: true })

    for (const entry of entries) {
      if (!entry.isDirectory()) continue

      const moduleFolder = entry.name
      const modulePath = join(modulesDir, moduleFolder)
      const manifestPath = join(modulePath, 'module.json')
      const pagePathTsx = join(modulePath, 'app', 'page.tsx')
      const pagePathJsx = join(modulePath, 'app', 'page.jsx')

      // Check if module.json exists
      if (!existsSync(manifestPath)) {
        continue
      }

      // Read module ID from manifest
      let moduleId: string
      try {
        const manifestContent = await readFile(manifestPath, 'utf-8')
        const manifest = JSON.parse(manifestContent)
        moduleId = manifest.id
        if (!moduleId) {
          continue
        }
      } catch {
        continue
      }

      // Check if app/page.tsx or app/page.jsx exists
      if (!existsSync(pagePathTsx) && !existsSync(pagePathJsx)) {
        continue
      }

      modules.push({ id: moduleId, dirName, folder: moduleFolder })
    }
  } catch (error) {
    console.error(`[Registry] Failed to scan ${dirName}:`, error)
  }

  return modules
}

/**
 * Scan all module directories with override precedence
 */
async function scanAllModules(): Promise<Map<string, { dirName: string; folder: string }>> {
  const moduleMap = new Map<string, { dirName: string; folder: string }>()

  for (const dirName of MODULE_DIRECTORIES) {
    const modules = await scanModulesDirectory(dirName)

    for (const mod of modules) {
      // Only add if not already present (custom takes precedence)
      if (!moduleMap.has(mod.id)) {
        moduleMap.set(mod.id, { dirName: mod.dirName, folder: mod.folder })
      }
    }
  }

  return moduleMap
}

/**
 * Generate the TypeScript registry content
 */
function generateRegistryContent(moduleMap: Map<string, { dirName: string; folder: string }>): string {
  const entries = Array.from(moduleMap.entries()).sort((a, b) => a[0].localeCompare(b[0]))

  const imports = entries.map(([id, { dirName, folder }]) =>
    `  '${id}': () => import('@/${dirName}/${folder}/app/page'),`
  ).join('\n')

  const moduleIds = entries.map(([id]) => id)

  return `/**
 * Auto-Generated Module Pages Registry
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: lib/modules/regenerate-registry.ts
 * Generated at: ${new Date().toISOString()}
 *
 * This file is auto-generated before each build to ensure
 * all modules in /modules-custom and /modules-core are registered for dynamic routing.
 * Modules in modules-custom take precedence over modules-core with the same ID.
 *
 * To regenerate: npm run generate-module-registry
 */

export const MODULE_PAGES: Record<string, any> = {
${imports}
}

/**
 * List of all registered module IDs
 */
export const REGISTERED_MODULE_IDS = [
  ${moduleIds.map(id => `'${id}'`).join(',\n  ')}
] as const

/**
 * Check if a module is registered
 */
export function isModuleRegistered(moduleId: string): boolean {
  return moduleId in MODULE_PAGES
}
`
}

/**
 * Regenerate the module registry file
 *
 * @returns Object with success status and module count
 */
export async function regenerateModuleRegistry(): Promise<{
  success: boolean
  moduleCount: number
  error?: string
}> {
  try {
    // Ensure output directory exists
    const outputDir = dirname(OUTPUT_FILE)
    if (!existsSync(outputDir)) {
      await mkdir(outputDir, { recursive: true })
    }

    // Scan all modules
    const moduleMap = await scanAllModules()

    // Generate registry content
    const content = generateRegistryContent(moduleMap)

    // Write to file
    await writeFile(OUTPUT_FILE, content, 'utf-8')

    return {
      success: true,
      moduleCount: moduleMap.size
    }
  } catch (error: any) {
    console.error('[Registry] Failed to regenerate:', error)
    return {
      success: false,
      moduleCount: 0,
      error: error.message
    }
  }
}
