// Shared .env.local helpers — server writes and client preview both render
// through these so the output stays identical. Callers MUST pre-reject values
// containing `\r`, `\n`, or `\x00`; `formatEnvValue` quotes and escapes
// everything else, but a newline in a value would still break the file.

import type { DbMode } from '@/lib/db/mode'

// Raw values without spaces, `#`, or quotes are written bare; anything else
// is double-quote-wrapped with `"` and `\` escaped.
export function formatEnvValue(value: string): string {
  if (value === "") return ""
  if (/^[A-Za-z0-9_\-./:@]+$/.test(value)) return value
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
  return `"${escaped}"`
}

// Upsert KEY=VALUE pairs in a dotenv-format string. null value removes the key.
export function upsertEnvVars(
  source: string,
  updates: Record<string, string | null>,
): string {
  const lines = source.split(/\r?\n/)
  const seen = new Set<string>()

  const result: string[] = []
  for (const line of lines) {
    const match = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=/)
    if (match && Object.prototype.hasOwnProperty.call(updates, match[1])) {
      const key = match[1]
      seen.add(key)
      const nextValue = updates[key]
      if (nextValue === null) {
        continue
      }
      result.push(`${key}=${formatEnvValue(nextValue)}`)
      continue
    }
    result.push(line)
  }

  const appended: string[] = []
  for (const [key, value] of Object.entries(updates)) {
    if (seen.has(key) || value === null) continue
    appended.push(`${key}=${formatEnvValue(value)}`)
  }

  if (appended.length > 0) {
    while (result.length > 0 && result[result.length - 1].trim() === "") {
      result.pop()
    }
    if (result.length > 0) {
      result.push("")
    }
    result.push(...appended)
  }

  let output = result.join("\n")
  if (!output.endsWith("\n")) output += "\n"
  return output
}

export interface WelcomeEnvFields {
  betterAuthSecret?: string
  databaseUrl?: string
  supabaseUrl?: string
  supabaseAnonKey?: string
  supabaseSecretKey?: string
  adminEmail?: string
  adminPassword?: string
  resendApiKey?: string
  resendWebhookSecret?: string
}

// Renders the .env.local content based on database mode.
//
// - postgres:       DATABASE_URL only, no Supabase vars
// - supabaselocal:  Points to .env.supabase.local (auto-generated by CLI)
// - supabasecloud:  Full Supabase vars from user input
export function renderEnvFile(
  fields: WelcomeEnvFields,
  options: { dbMode?: DbMode } = {},
): string {
  const lines: string[] = []
  const write = (key: string, value: string | undefined): void => {
    lines.push(`${key}=${value === undefined ? "" : formatEnvValue(value)}`)
  }
  const trimmed = (v: string | undefined): string | undefined => {
    if (v === undefined) return undefined
    const s = v.trim()
    return s === "" ? undefined : s
  }

  const dbMode = options.dbMode

  lines.push("# ARI Application Environment Configuration")
  lines.push("# Generated by onboarding wizard")
  lines.push("")

  // Persist ARI_DB_MODE if known
  if (dbMode) {
    write("ARI_DB_MODE", dbMode)
    lines.push("")
  }

  lines.push(
    "## Set this to localhost. On your host (e.g., Vercel) set it to your domain name.",
  )
  lines.push("NEXT_PUBLIC_APP_URL=http://localhost:3000")
  lines.push("")

  lines.push("# Better Auth Configuration (Required)")
  write("BETTER_AUTH_SECRET", trimmed(fields.betterAuthSecret) ?? "")
  lines.push("BETTER_AUTH_URL=http://localhost:3000")
  lines.push("")

  const dbUrl = trimmed(fields.databaseUrl)

  if (dbMode === 'postgres') {
    // PostgreSQL mode — DATABASE_URL only, no Supabase vars
    lines.push("# Database")
    write("DATABASE_URL", dbUrl ?? "postgresql://localhost:5432/ari")
    lines.push("DATABASE_POOL_MAX=")
    lines.push("")
  } else if (dbMode === 'supabaselocal' && !dbUrl) {
    // Local Supabase — vars come from .env.supabase.local
    lines.push(
      "# Supabase: Using local Supabase (configured via .env.supabase.local)",
    )
    lines.push(
      "# To use a remote Supabase instance, add DATABASE_URL, NEXT_PUBLIC_SUPABASE_URL,",
    )
    lines.push(
      "# NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY, and SUPABASE_SECRET_KEY here.",
    )
    lines.push("")
  } else {
    // supabasecloud (or fallback) — full Supabase vars from user input
    lines.push("## PRODUCTION SUPABASE")
    write("DATABASE_URL", dbUrl ?? "")
    lines.push("DATABASE_POOL_MAX=")
    write("NEXT_PUBLIC_SUPABASE_URL", trimmed(fields.supabaseUrl) ?? "")
    write(
      "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
      trimmed(fields.supabaseAnonKey) ?? "",
    )
    write("SUPABASE_SECRET_KEY", trimmed(fields.supabaseSecretKey) ?? "")
    lines.push("")
  }

  lines.push("# Allow the user to take manual backups on the /settings page.")
  lines.push("# Default: true")
  lines.push("ALLOW_BACKUP_OPERATIONS=true")
  lines.push("")

  lines.push("## Optional: Pre-fill the license key for module activation.")
  lines.push("## If set, users won't need to manually enter it in the UI.")
  lines.push("ARI_LICENSE_KEY=")
  lines.push("")

  lines.push("## Optionally restrict Access to specific IP addresses.")
  lines.push("## Example: ALLOWED_IPS=1.1.1.1,8.8.8.8")
  lines.push("## 127.0.0.1 and localhost and ::1 are always allowed.")
  lines.push("ALLOWED_IPS=")
  lines.push("")

  lines.push("# Top Bar Customization (optional)")
  lines.push('# NEXT_PUBLIC_TOP_BAR_MESSAGE="Custom Message"')
  lines.push('# NEXT_PUBLIC_TOP_BAR_COLOR="#c00"')
  lines.push("")

  const adminEmail = trimmed(fields.adminEmail)
  const adminPassword = trimmed(fields.adminPassword)
  if (adminEmail && adminPassword) {
    lines.push("# Initial Admin Account (First-Run Bootstrap)")
    lines.push(
      "# These credentials are used ONLY to create your admin account when the user table is empty.",
    )
    lines.push(
      "# After your account is created on first run, you can safely delete these two lines.",
    )
    write("ARI_FIRST_RUN_ADMIN_EMAIL", adminEmail)
    write("ARI_FIRST_RUN_ADMIN_PASSWORD", adminPassword)
    lines.push("")
  }

  const resendApiKey = trimmed(fields.resendApiKey)
  if (resendApiKey) {
    lines.push("# Resend Email Service")
    write("RESEND_API_KEY", resendApiKey)
    const resendWebhook = trimmed(fields.resendWebhookSecret)
    if (resendWebhook) {
      write("RESEND_WEBHOOK_SECRET", resendWebhook)
    }
    lines.push("")
  }

  return lines.join("\n")
}
