import { describe, it, expect } from 'vitest'
import {
  generateCreateTable,
  generateForeignKeyStatements,
  generateIndexStatements,
} from '@/lib/backup/ddl'
import type { ColumnDef, TableDefinition } from '@/lib/backup/schema-discovery'

const col = (partial: Partial<ColumnDef> & { name: string; dataType: string }): ColumnDef => ({
  notNull: false,
  defaultExpr: null,
  identity: '',
  ...partial,
})

const table = (partial: Partial<TableDefinition> & { name: string }): TableDefinition => ({
  columns: [],
  primaryKey: [],
  constraints: [],
  indexes: [],
  ...partial,
})

describe('generateCreateTable', () => {
  it('emits exact types and verbatim defaults, including string/jsonb/array defaults', () => {
    const { sql, warnings } = generateCreateTable(
      table({
        name: 'tasks',
        columns: [
          col({ name: 'id', dataType: 'uuid', notNull: true, defaultExpr: 'gen_random_uuid()' }),
          col({ name: 'status', dataType: 'text', notNull: true, defaultExpr: "'Pending'::text" }),
          col({ name: 'meta', dataType: 'jsonb', defaultExpr: "'{}'::jsonb" }),
          col({ name: 'assignees', dataType: 'text[]', defaultExpr: "'{}'::text[]" }),
          col({ name: 'counts', dataType: 'integer[]' }),
          col({ name: 'label', dataType: 'character varying(50)' }),
          col({ name: 'price', dataType: 'numeric(10,4)' }),
          col({ name: 'created_at', dataType: 'timestamp with time zone', notNull: true, defaultExpr: 'now()' }),
        ],
        constraints: [
          { name: 'tasks_pkey', type: 'p', definition: 'PRIMARY KEY (id)', referencedTable: null },
        ],
      })
    )
    expect(warnings).toEqual([])
    expect(sql).toContain('CREATE TABLE "tasks" (')
    expect(sql).toContain('"id" uuid NOT NULL DEFAULT gen_random_uuid(),')
    expect(sql).toContain(`"status" text NOT NULL DEFAULT 'Pending'::text,`)
    expect(sql).toContain(`"meta" jsonb DEFAULT '{}'::jsonb,`)
    expect(sql).toContain(`"assignees" text[] DEFAULT '{}'::text[],`)
    expect(sql).toContain('"counts" integer[],')
    expect(sql).toContain('"label" character varying(50),')
    expect(sql).toContain('"price" numeric(10,4),')
    expect(sql).toContain('"created_at" timestamp with time zone NOT NULL DEFAULT now(),')
    expect(sql).toContain('CONSTRAINT "tasks_pkey" PRIMARY KEY (id)')
    expect(sql.trimEnd().endsWith(');')).toBe(true)
  })

  it('emits identity columns and keeps UNIQUE/CHECK inline while excluding FKs', () => {
    const { sql } = generateCreateTable(
      table({
        name: 'user',
        columns: [
          col({ name: 'id', dataType: 'text', notNull: true }),
          col({ name: 'seq_a', dataType: 'integer', notNull: true, identity: 'a' }),
          col({ name: 'seq_d', dataType: 'integer', notNull: true, identity: 'd' }),
        ],
        constraints: [
          { name: 'user_email_key', type: 'u', definition: 'UNIQUE (email)', referencedTable: null },
          { name: 'user_check', type: 'c', definition: 'CHECK ((length(id) > 0))', referencedTable: null },
          { name: 'user_fk', type: 'f', definition: 'FOREIGN KEY (org_id) REFERENCES orgs(id)', referencedTable: 'orgs' },
        ],
      })
    )
    expect(sql).toContain('"seq_a" integer GENERATED ALWAYS AS IDENTITY NOT NULL')
    expect(sql).toContain('"seq_d" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(sql).toContain('CONSTRAINT "user_email_key" UNIQUE (email)')
    expect(sql).toContain('CONSTRAINT "user_check" CHECK ((length(id) > 0))')
    expect(sql).not.toContain('FOREIGN KEY')
  })

  it('maps nextval defaults on integer types to SERIAL variants (defensive)', () => {
    const { sql, warnings } = generateCreateTable(
      table({
        name: 'legacy',
        columns: [
          col({ name: 'a', dataType: 'smallint', notNull: true, defaultExpr: "nextval('legacy_a_seq'::regclass)" }),
          col({ name: 'b', dataType: 'integer', notNull: true, defaultExpr: "nextval('legacy_b_seq'::regclass)" }),
          col({ name: 'c', dataType: 'bigint', notNull: true, defaultExpr: "nextval('legacy_c_seq'::regclass)" }),
        ],
      })
    )
    expect(warnings).toEqual([])
    expect(sql).toContain('"a" SMALLSERIAL')
    expect(sql).toContain('"b" SERIAL')
    expect(sql).toContain('"c" BIGSERIAL')
    expect(sql).not.toContain('nextval')
  })

  it('drops a nextval default on a non-integer type with a warning', () => {
    const { sql, warnings } = generateCreateTable(
      table({
        name: 'odd',
        columns: [col({ name: 'x', dataType: 'uuid', notNull: true, defaultExpr: "nextval('odd_seq'::regclass)" })],
      })
    )
    expect(sql).toContain('"x" uuid NOT NULL')
    expect(sql).not.toContain('nextval')
    expect(warnings.some((w) => w.includes('dropped sequence default'))).toBe(true)
  })

  it('warns on non-built-in column types but still exports them verbatim', () => {
    const { sql, warnings } = generateCreateTable(
      table({ name: 'moods', columns: [col({ name: 'mood', dataType: 'mood_enum' })] })
    )
    expect(sql).toContain('"mood" mood_enum')
    expect(warnings).toEqual(['moods.mood: non-built-in type "mood_enum" exported verbatim'])
  })
})

describe('generateForeignKeyStatements', () => {
  const documents = table({
    name: 'documents',
    constraints: [
      {
        name: 'documents_user_fk',
        type: 'f',
        definition: 'FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE',
        referencedTable: 'user',
      },
      {
        name: 'documents_tag_fk',
        type: 'f',
        definition: 'FOREIGN KEY (tag_id, user_id) REFERENCES document_tags(id, user_id)',
        referencedTable: 'document_tags',
      },
      { name: 'documents_pkey', type: 'p', definition: 'PRIMARY KEY (id)', referencedTable: null },
    ],
  })
  const nodes = table({
    name: 'nodes',
    constraints: [
      {
        name: 'nodes_parent_fk',
        type: 'f',
        definition: 'FOREIGN KEY (parent_id) REFERENCES nodes(id) ON DELETE CASCADE',
        referencedTable: 'nodes',
      },
    ],
  })

  it('emits single-line validating ALTERs for FKs whose target is in the backup set', () => {
    const { statements, skipped } = generateForeignKeyStatements([
      documents,
      nodes,
      table({ name: 'user' }),
      table({ name: 'document_tags' }),
    ])
    expect(skipped).toEqual([])
    expect(statements).toEqual([
      'ALTER TABLE "documents" ADD CONSTRAINT "documents_user_fk" FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;',
      'ALTER TABLE "documents" ADD CONSTRAINT "documents_tag_fk" FOREIGN KEY (tag_id, user_id) REFERENCES document_tags(id, user_id);',
      'ALTER TABLE "nodes" ADD CONSTRAINT "nodes_parent_fk" FOREIGN KEY (parent_id) REFERENCES nodes(id) ON DELETE CASCADE;',
    ])
    for (const statement of statements) {
      expect(statement.includes('\n')).toBe(false)
      expect(statement.endsWith(';')).toBe(true)
    }
  })

  it('skips and reports FKs whose referenced table is not in the set', () => {
    const { statements, skipped } = generateForeignKeyStatements([documents, table({ name: 'user' })])
    expect(statements).toHaveLength(1)
    expect(skipped).toEqual([
      'documents.documents_tag_fk (references document_tags, not in backup set)',
    ])
  })

  it('reports FKs with an unknown referenced table', () => {
    const orphan = table({
      name: 'orphan',
      constraints: [{ name: 'orphan_fk', type: 'f', definition: 'FOREIGN KEY (x) REFERENCES gone(id)', referencedTable: null }],
    })
    const { statements, skipped } = generateForeignKeyStatements([orphan])
    expect(statements).toEqual([])
    expect(skipped).toEqual(['orphan.orphan_fk (references unknown, not in backup set)'])
  })
})

describe('generateIndexStatements', () => {
  it('emits verbatim indexdef statements with semicolons', () => {
    const statements = generateIndexStatements(
      table({
        name: 'tasks',
        indexes: [
          { name: 'idx_a', definition: 'CREATE INDEX idx_a ON public.tasks USING btree (user_id)' },
          { name: 'idx_b', definition: 'CREATE UNIQUE INDEX idx_b ON public.tasks USING btree (lower(title))' },
        ],
      })
    )
    expect(statements).toEqual([
      'CREATE INDEX idx_a ON public.tasks USING btree (user_id);',
      'CREATE UNIQUE INDEX idx_b ON public.tasks USING btree (lower(title));',
    ])
  })

  it('returns nothing for a table without extra indexes', () => {
    expect(generateIndexStatements(table({ name: 'plain' }))).toEqual([])
  })
})
