/**
 * Auto-Generated Relations Barrel
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: scripts/generate-module-registry.js
 * Generated at: 2026-03-30T19:26:46.825Z
 *
 * Re-exports core relations + all installed module relations.
 * To regenerate: npm run generate-module-registry
 */

export * from './core-relations'
export * from '@/modules/hyrox/database/relations'
export * from '@/modules/knowledge-manager/database/relations'
export * from '@/modules/tasks/database/relations'
export * from '@/modules/winter-arc/database/relations'
