/**
 * Auto-Generated Relations Barrel
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: scripts/generate-module-registry.js
 * Generated at: 2026-04-05T21:24:16.546Z
 *
 * Re-exports core relations + all installed module relations.
 * To regenerate: npm run generate-module-registry
 */

export * from './core-relations'

