/**
 * Auto-Generated Schema Barrel
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: scripts/generate-module-registry.js
 * To regenerate: npm run generate-module-registry
 *
 * Re-exports core schema + all installed module schema.
 */

export * from './core-schema'
export * from '@/modules/brainstorm/database/schema'
export * from '@/modules/module-template/database/schema'
export * from '@/modules/music-player/database/schema'
export * from '@/modules/notepad/database/schema'
export * from '@/modules/quotes/database/schema'
export * from '@/modules/tasks/database/schema'
