/**
 * Auto-Generated Schema Barrel
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: scripts/generate-module-registry.js
 * Generated at: 2026-04-06T00:59:46.432Z
 *
 * Re-exports core schema + all installed module schema.
 * To regenerate: npm run generate-module-registry
 */

export * from './core-schema'
export * from '@/modules/music-player/database/schema'
export * from '@/modules/notepad/database/schema'
export * from '@/modules/quotes/database/schema'
export * from '@/modules/tasks/database/schema'
