/**
 * Module API Catch-All Route
 *
 * Dynamically imports and executes module API handlers using a registry pattern.
 * Proxies requests to module API routes in /modules-core/[module]/api/
 *
 * URL Pattern: /api/modules/[module]/[[...path]]
 * Examples:
 *   /api/modules/contacts → /modules-core/contacts/api/route.ts
 *   /api/modules/contacts/123 → /modules-core/contacts/api/[id]/route.ts
 *   /api/modules/module-template/data → /modules-core/module-template/api/data/route.ts
 *
 * The MODULE_API_ROUTES registry is auto-generated by scripts/generate-module-registry.js.
 * Run that script (or hit POST /api/modules/refresh) after adding new module API routes.
 *
 * AUTH & ENABLEMENT: Authenticated routes require a valid Better Auth session
 * or ARI API key AND the target module to be enabled for that user. Disabled
 * (or never-enabled) modules return 403. Enablement is read from
 * module_settings on every request, so toggling a module takes effect
 * immediately — no restart needed.
 *
 * PUBLIC ROUTES: Routes configured in module.json's publicRoutes array are
 * accessible without authentication and skip the module-enabled check (there
 * is no user context to check against). Each public route handler must
 * implement its own security.
 */

import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import moduleManifest from '@/lib/generated/module-manifest.json'
import { MODULE_API_ROUTES } from '@/lib/generated/module-api-registry'
import { recordApiKeyUsage, hashApiKey, lookupApiKey } from '@/lib/api-keys'
import { getAuthenticatedUser } from '@/lib/auth-helpers'
import { getEnabledModule } from '@/lib/modules/module-registry'

/**
 * Public routes from module manifest
 * These routes bypass authentication but must implement their own security
 */
interface PublicRouteEntry {
  moduleId: string
  path: string
  methods: string[]
}

const publicRoutes: PublicRouteEntry[] = (moduleManifest.publicRoutes || []) as PublicRouteEntry[]

/** Identity of the API key behind a request, once auth has resolved it. */
interface ApiKeyMeta {
  id: string
  userId: string
  ipAddress: string | null
  userAgent: string | null
}

/**
 * Check if a route is configured as public in module.json
 */
function isPublicRoute(moduleId: string, apiPath: string, method: string): boolean {
  return publicRoutes.some(
    route =>
      route.moduleId === moduleId &&
      route.path === apiPath &&
      route.methods.includes(method.toUpperCase())
  )
}

/**
 * Attribute usage to the presented API key even when the request was not
 * key-authenticated — rejected keys (e.g. IP-allowlist block) and public
 * routes. lookupApiKey validates hash/revocation/expiry but NOT the IP
 * allowlist, so probes of a valid-but-blocked key stay visible in the usage
 * log (the key owner's only compromise signal). Cheap: lookupApiKey has a
 * 5s in-process cache and recordApiKeyUsage is fire-and-forget.
 */
async function recordUsageByKeyValue(
  request: NextRequest,
  rawKey: string,
  endpoint: string,
  method: string,
  statusCode: number,
): Promise<void> {
  try {
    const keyRow = await lookupApiKey(hashApiKey(rawKey))
    if (!keyRow) return
    recordApiKeyUsage({
      apiKeyId: keyRow.id,
      userId: keyRow.userId,
      endpoint,
      method,
      statusCode,
      ipAddress: request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
        || request.headers.get('x-real-ip')
        || null,
      userAgent: request.headers.get('user-agent'),
    })
  } catch (err) {
    console.error('[Module API] Failed to log API key usage:', err)
  }
}

/**
 * Handle API requests using the MODULE_API_ROUTES registry
 */
async function handleRequest(
  request: NextRequest,
  method: string,
  params: Promise<{ module: string; path?: string[] }>
) {
  const { module, path } = await params

  // Build API path from segments (e.g., ['items'] -> 'items', undefined -> '')
  const pathArray = path || []
  const apiPath = pathArray.join('/')

  const apiKeyValue = request.headers.get('x-api-key')
  const endpoint = `/api/modules/${module}${apiPath ? '/' + apiPath : ''}`

  // Hoisted out of the try so the catch-all 500 handler can still attribute the
  // request to its API key.
  let isPublic = false
  let apiKeyMeta: ApiKeyMeta | null = null

  /**
   * Record this request against its API key, if one is behind it.
   *
   * `preAuth` marks the paths that return before credentials are verified
   * (unknown module / unknown route), where no session could own the request
   * and a presented key is therefore safe to attribute. Otherwise a raw key is
   * only attributed on public routes — a session request carrying a stray
   * x-api-key header must not be logged against that key.
   */
  const logUsage = async (statusCode: number, preAuth = false): Promise<void> => {
    const meta: ApiKeyMeta | null = apiKeyMeta
    if (meta) {
      recordApiKeyUsage({
        apiKeyId: meta.id,
        userId: meta.userId,
        endpoint,
        method,
        statusCode,
        ipAddress: meta.ipAddress,
        userAgent: meta.userAgent,
      })
      return
    }
    if (apiKeyValue && (preAuth || isPublic)) {
      await recordUsageByKeyValue(request, apiKeyValue, endpoint, method, statusCode)
    }
  }

  try {
    // Check if this is a public route (configured in module.json publicRoutes)
    // Public routes skip authentication but must implement their own security
    isPublic = isPublicRoute(module, apiPath, method)

    if (!isPublic) {
      // Fast-path rejection for fully anonymous requests — no DB work.
      // Full credential verification + the per-user module-enabled check
      // happen after route resolution below, so unknown modules/routes
      // still return 404 first.
      const cookieStore = await cookies()
      const sessionCookie = process.env.NODE_ENV === 'production'
        ? cookieStore.get('__Secure-better-auth.session_token')
        : cookieStore.get('better-auth.session_token')
      if (!sessionCookie && !apiKeyValue) {
        return NextResponse.json(
          { error: 'Unauthorized' },
          { status: 401 }
        )
      }
    }

    // Look up module in registry
    const moduleRoutes = MODULE_API_ROUTES[module]
    if (!moduleRoutes) {
      console.error(`[Module API] Module '${module}' not found in registry`)
      await logUsage(404, true)
      return NextResponse.json(
        { error: `API routes not registered for module: ${module}` },
        { status: 404 }
      )
    }

    // Look up specific route in module
    // Handle empty path (base route), named routes, and dynamic [id] routes
    let routeLoader = moduleRoutes[apiPath]
    let dynamicParams: any = null // Track if we need to transform params

    // If not found and path has single segment, try [id] route for dynamic IDs
    if (!routeLoader && pathArray.length === 1 && moduleRoutes['[id]']) {
      routeLoader = moduleRoutes['[id]']
      // Transform params: { module, path: ['uuid'] } -> { id: 'uuid' }
      dynamicParams = Promise.resolve({ id: pathArray[0] })
    }

    // If not found and path has multiple segments, try nested dynamic routes
    // Try replacing each segment with [id] to match patterns like:
    //   ['data', '123'] -> 'data/[id]'
    //   ['files', '123', 'download'] -> 'files/[id]/download'
    if (!routeLoader && pathArray.length > 1) {
      for (let i = pathArray.length - 1; i >= 0; i--) {
        const candidate = [...pathArray]
        candidate[i] = '[id]'
        const patternPath = candidate.join('/')
        if (moduleRoutes[patternPath]) {
          routeLoader = moduleRoutes[patternPath]
          dynamicParams = Promise.resolve({ id: pathArray[i] })
          break
        }
      }
    }

    // If still not found and path is empty, try empty string route
    if (!routeLoader && pathArray.length === 0 && moduleRoutes['']) {
      routeLoader = moduleRoutes['']
    }

    if (!routeLoader) {
      console.error(`[Module API] Route '${apiPath}' not found in module '${module}' registry`)
      await logUsage(404, true)
      return NextResponse.json(
        { error: `API route not found: /api/modules/${module}/${apiPath}` },
        { status: 404 }
      )
    }

    // Full credential verification + per-user module-enabled enforcement
    // (mirrors the module page catch-all in app/(app)/[module]/[[...slug]]).
    // getEnabledModule() also runs the schema self-heal gate — it re-runs the
    // module's schema.sql when the stored install hash differs — and, because
    // the resolved userId is passed explicitly, it works for API-key clients
    // too (a sessionless getEnabledModule() call would return null).
    // Public routes skip this: they have no user context, so a module's
    // public routes remain reachable while the module is disabled.
    if (!isPublic) {
      const authResult = await getAuthenticatedUser()
      if (!authResult.user) {
        // A rejected request may still carry a real key (e.g. valid key from
        // a non-allowlisted IP) — record it so the key owner can see probes.
        await logUsage(401, true)
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
      }
      apiKeyMeta = 'apiKey' in authResult ? authResult.apiKey ?? null : null

      const enabledModule = await getEnabledModule(module, authResult.user.id)
      if (!enabledModule) {
        await logUsage(403)
        return NextResponse.json(
          { error: `Module '${module}' is disabled` },
          { status: 403 }
        )
      }
    }

    // Load the route handler using the static import
    const handler = await routeLoader()

    // Check if the HTTP method is supported by this handler
    if (!handler[method]) {
      await logUsage(405)
      return NextResponse.json(
        { error: `Method ${method} not allowed` },
        { status: 405 }
      )
    }

    // Execute the handler
    const result = await handler[method](request, { params: dynamicParams || params })

    // Log API key usage before returning the response. apiKeyMeta is only set
    // when the request actually authenticated via x-api-key, so session
    // requests carrying a stray key header are not attributed to the key.
    // Public routes skip auth entirely, so a key presented there is
    // attributed by value instead — keys used only against public endpoints
    // must not look dormant in Settings → API.
    // recordApiKeyUsage is fire-and-forget and catches its own errors.
    await logUsage(result.status)

    return result
  } catch (error: unknown) {
    // Log error for debugging
    console.error(`[Module API ${module}/${apiPath}] Error:`, error)

    // In development, surface the real error message in the response so
    // /health and the browser network panel show what actually broke. In
    // production, keep the generic message — error details may leak schema
    // names, constraint names, or row contents.
    const isDev = process.env.NODE_ENV !== 'production'
    const body: Record<string, unknown> = { error: 'Internal server error' }
    if (isDev && error instanceof Error) {
      body.message = error.message
    }
    // A key-authenticated request that throws must still appear in the audit
    // trail — otherwise the most interesting requests are the invisible ones.
    await logUsage(500)
    return NextResponse.json(body, { status: 500 })
  }
}

/**
 * GET handler
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'GET', params)
}

/**
 * POST handler
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'POST', params)
}

/**
 * PUT handler
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'PUT', params)
}

/**
 * DELETE handler
 */
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'DELETE', params)
}

/**
 * PATCH handler
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'PATCH', params)
}
