/**
 * Module API Catch-All Route
 *
 * Dynamically imports and executes module API handlers using a registry pattern.
 * Proxies requests to module API routes in /modules-core/[module]/api/
 *
 * URL Pattern: /api/modules/[module]/[[...path]]
 * Examples:
 *   /api/modules/contacts → /modules-core/contacts/api/route.ts
 *   /api/modules/contacts/123 → /modules-core/contacts/api/[id]/route.ts
 *   /api/modules/module-template/data → /modules-core/module-template/api/data/route.ts
 *
 * The MODULE_API_ROUTES registry is auto-generated by scripts/generate-module-registry.js.
 * Run that script (or hit POST /api/modules/refresh) after adding new module API routes.
 *
 * PUBLIC ROUTES: Routes configured in module.json's publicRoutes array are
 * accessible without authentication. Security is enforced by the route handler
 * using the createPublicRouteHandler wrapper.
 */

import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import moduleManifest from '@/lib/generated/module-manifest.json'
import { MODULE_API_ROUTES } from '@/lib/generated/module-api-registry'
import { recordApiKeyUsage } from '@/lib/api-keys'

/**
 * Public routes from module manifest
 * These routes bypass authentication but must implement their own security
 */
interface PublicRouteEntry {
  moduleId: string
  path: string
  methods: string[]
}

const publicRoutes: PublicRouteEntry[] = (moduleManifest.publicRoutes || []) as PublicRouteEntry[]

/**
 * Check if a route is configured as public in module.json
 */
function isPublicRoute(moduleId: string, apiPath: string, method: string): boolean {
  return publicRoutes.some(
    route =>
      route.moduleId === moduleId &&
      route.path === apiPath &&
      route.methods.includes(method.toUpperCase())
  )
}

/**
 * Handle API requests using the MODULE_API_ROUTES registry
 */
async function handleRequest(
  request: NextRequest,
  method: string,
  params: Promise<{ module: string; path?: string[] }>
) {
  const { module, path } = await params

  // Build API path from segments (e.g., ['items'] -> 'items', undefined -> '')
  const pathArray = path || []
  const apiPath = pathArray.join('/')

  const apiKeyValue = request.headers.get('x-api-key')

  try {
    // Check if this is a public route (configured in module.json publicRoutes)
    // Public routes skip authentication but must implement their own security
    const isPublic = isPublicRoute(module, apiPath, method)

    if (!isPublic) {
      // Lightweight auth check — avoids a DB round-trip here.
      // The actual auth verification + module-enabled check happens
      // inside each module handler via getAuthenticatedUser().
      const cookieStore = await cookies()
      const sessionCookie = cookieStore.get('better-auth.session_token')
        || cookieStore.get('__Secure-better-auth.session_token')
      if (!sessionCookie && !apiKeyValue) {
        return NextResponse.json(
          { error: 'Unauthorized' },
          { status: 401 }
        )
      }
    }

    // Look up module in registry
    const moduleRoutes = MODULE_API_ROUTES[module]
    if (!moduleRoutes) {
      console.error(`[Module API] Module '${module}' not found in registry`)
      return NextResponse.json(
        { error: `API routes not registered for module: ${module}` },
        { status: 404 }
      )
    }

    // Look up specific route in module
    // Handle empty path (base route), named routes, and dynamic [id] routes
    let routeLoader = moduleRoutes[apiPath]
    let dynamicParams: any = null // Track if we need to transform params

    // If not found and path has single segment, try [id] route for dynamic IDs
    if (!routeLoader && pathArray.length === 1 && moduleRoutes['[id]']) {
      routeLoader = moduleRoutes['[id]']
      // Transform params: { module, path: ['uuid'] } -> { id: 'uuid' }
      dynamicParams = Promise.resolve({ id: pathArray[0] })
    }

    // If not found and path has multiple segments, try nested dynamic routes
    // Try replacing each segment with [id] to match patterns like:
    //   ['data', '123'] -> 'data/[id]'
    //   ['files', '123', 'download'] -> 'files/[id]/download'
    if (!routeLoader && pathArray.length > 1) {
      for (let i = pathArray.length - 1; i >= 0; i--) {
        const candidate = [...pathArray]
        candidate[i] = '[id]'
        const patternPath = candidate.join('/')
        if (moduleRoutes[patternPath]) {
          routeLoader = moduleRoutes[patternPath]
          dynamicParams = Promise.resolve({ id: pathArray[i] })
          break
        }
      }
    }

    // If still not found and path is empty, try empty string route
    if (!routeLoader && pathArray.length === 0 && moduleRoutes['']) {
      routeLoader = moduleRoutes['']
    }

    if (!routeLoader) {
      console.error(`[Module API] Route '${apiPath}' not found in module '${module}' registry`)
      return NextResponse.json(
        { error: `API route not found: /api/modules/${module}/${apiPath}` },
        { status: 404 }
      )
    }

    // Load the route handler using the static import
    const handler = await routeLoader()

    // Check if the HTTP method is supported by this handler
    if (!handler[method]) {
      return NextResponse.json(
        { error: `Method ${method} not allowed` },
        { status: 405 }
      )
    }

    // Execute the handler
    const result = await handler[method](request, { params: dynamicParams || params })

    // Log API key usage (fire-and-forget) — no extra DB lookup needed,
    // getAuthenticatedUser() inside the handler already resolved the key
    if (apiKeyValue) {
      const endpoint = `/api/modules/${module}${apiPath ? '/' + apiPath : ''}`
      // Read API key metadata set by getAuthenticatedUser() via response header
      // We pass request info so the logging in auth-helpers has it available
      const { hashApiKey, lookupApiKey } = await import('@/lib/api-keys')
      const keyHash = hashApiKey(apiKeyValue)
      lookupApiKey(keyHash).then((keyRow) => {
        if (keyRow) {
          recordApiKeyUsage({
            apiKeyId: keyRow.id,
            userId: keyRow.userId,
            endpoint,
            method,
            statusCode: result.status,
            ipAddress: request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
              || request.headers.get('x-real-ip')
              || null,
            userAgent: request.headers.get('user-agent'),
          })
        }
      }).catch(() => {})
    }

    return result
  } catch (error: any) {
    // Log error for debugging
    console.error(`[Module API ${module}/${apiPath}] Error:`, error)

    // Generic error response
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    )
  }
}

/**
 * GET handler
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'GET', params)
}

/**
 * POST handler
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'POST', params)
}

/**
 * PUT handler
 */
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'PUT', params)
}

/**
 * DELETE handler
 */
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'DELETE', params)
}

/**
 * PATCH handler
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ module: string; path?: string[] }> }
) {
  return handleRequest(request, 'PATCH', params)
}
