/**
 * DDL generation for backup export, from discovered TableDefinitions.
 *
 * - CREATE TABLE carries columns (exact catalog types + verbatim defaults)
 *   with PK / UNIQUE / CHECK constraints inline.
 * - Foreign keys are emitted separately as single-line
 *   `ALTER TABLE ... ADD CONSTRAINT ...;` statements, positioned AFTER data
 *   by the exporter (the import parser buckets them into `other`, executed
 *   last). They are plain validating ADDs: session_replication_role='replica'
 *   skips FK triggers during inserts, but ADD CONSTRAINT validates existing
 *   rows via a scan — a backup with orphaned rows fails the restore and
 *   rolls back rather than restoring silently corrupt data.
 * - Indexes are emitted verbatim from pg_indexes.indexdef, replacing the
 *   old column-name-guessing heuristic.
 *
 * Pure logic — no database access.
 */

import type { ColumnDef, TableDefinition } from './schema-discovery'

/** Built-in types the serializer/import round-trip is known-good for.
 *  Anything else (enums, tsvector, custom domains) still exports verbatim
 *  but is surfaced as a warning so the operator isn't surprised on restore. */
const KNOWN_TYPE_RE =
  /^(text|boolean|integer|bigint|smallint|real|double precision|numeric(\(\d+,\s*\d+\))?|character varying(\(\d+\))?|character\(\d+\)|uuid|date|time(stamp)?( with(out)? time zone)?|interval|json|jsonb|bytea)(\[\])*$/i

const SERIAL_TYPES: Record<string, string> = {
  smallint: 'SMALLSERIAL',
  integer: 'SERIAL',
  bigint: 'BIGSERIAL',
}

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`
}

function columnLine(column: ColumnDef, warnings: string[], tableName: string): string {
  if (!KNOWN_TYPE_RE.test(column.dataType)) {
    warnings.push(`${tableName}.${column.name}: non-built-in type "${column.dataType}" exported verbatim`)
  }

  // Defensive only — no serial/identity columns exist in the schema today.
  if (column.defaultExpr && /^nextval\(/.test(column.defaultExpr)) {
    const serial = SERIAL_TYPES[column.dataType.toLowerCase()]
    if (serial) {
      // SERIAL implies NOT NULL and carries its own sequence default.
      return `  ${quoteIdent(column.name)} ${serial}`
    }
    warnings.push(
      `${tableName}.${column.name}: dropped sequence default "${column.defaultExpr}" (no matching serial type)`
    )
    return `  ${quoteIdent(column.name)} ${column.dataType}${column.notNull ? ' NOT NULL' : ''}`
  }

  let line = `  ${quoteIdent(column.name)} ${column.dataType}`
  if (column.identity === 'a') line += ' GENERATED ALWAYS AS IDENTITY'
  if (column.identity === 'd') line += ' GENERATED BY DEFAULT AS IDENTITY'
  if (column.notNull) line += ' NOT NULL'
  if (column.defaultExpr && !column.identity) line += ` DEFAULT ${column.defaultExpr}`
  return line
}

/** Generate a CREATE TABLE with inline PK/UNIQUE/CHECK (FKs excluded). */
export function generateCreateTable(table: TableDefinition): { sql: string; warnings: string[] } {
  const warnings: string[] = []
  const lines = table.columns.map((column) => columnLine(column, warnings, table.name))

  for (const constraint of table.constraints) {
    if (constraint.type === 'f') continue // emitted post-data by generateForeignKeyStatements
    lines.push(`  CONSTRAINT ${quoteIdent(constraint.name)} ${constraint.definition}`)
  }

  const sql = `CREATE TABLE ${quoteIdent(table.name)} (\n${lines.join(',\n')}\n);`
  return { sql, warnings }
}

/**
 * Generate single-line FK statements for every FK whose referenced table is
 * also in the backup set; the rest are skipped and reported (boot/module
 * schema healing re-adds constraints that code owns).
 */
export function generateForeignKeyStatements(tables: TableDefinition[]): {
  statements: string[]
  skipped: string[]
} {
  const tableSet = new Set(tables.map((t) => t.name))
  const statements: string[] = []
  const skipped: string[] = []

  for (const table of tables) {
    for (const constraint of table.constraints) {
      if (constraint.type !== 'f') continue
      if (constraint.referencedTable && tableSet.has(constraint.referencedTable)) {
        statements.push(
          `ALTER TABLE ${quoteIdent(table.name)} ADD CONSTRAINT ${quoteIdent(constraint.name)} ${constraint.definition};`
        )
      } else {
        skipped.push(
          `${table.name}.${constraint.name} (references ${constraint.referencedTable ?? 'unknown'}, not in backup set)`
        )
      }
    }
  }

  return { statements, skipped }
}

/** Verbatim CREATE INDEX statements (already single-line from pg_indexes). */
export function generateIndexStatements(table: TableDefinition): string[] {
  return table.indexes.map((index) => `${index.definition};`)
}
